import { type FormulaSheet, type Formula } from "./index";

interface RawFormula {
  id: string;
  name: string;
  latex: string;
  description: string;
}

function cat(name: string, items: { name: string; latex: string; description: string }[]): { name: string; formulas: RawFormula[] } {
  return {
    name,
    formulas: items.map((f, i) => ({ id: `${name.toLowerCase().replace(/\s+/g, "-")}-${i + 1}`, ...f })),
  };
}

const MATH_CATEGORIES = [
  cat("Algebra", [
    { name: "Quadratic Formula", latex: "x = \\dfrac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}", description: "Solves ax² + bx + c = 0" },
    { name: "Difference of Two Squares", latex: "a^2 - b^2 = (a+b)(a-b)", description: "Factorising shortcut" },
    { name: "Perfect Square (sum)", latex: "(a+b)^2 = a^2 + 2ab + b^2", description: "Expanding a squared sum" },
    { name: "Perfect Square (difference)", latex: "(a-b)^2 = a^2 - 2ab + b^2", description: "Expanding a squared difference" },
    { name: "Sum of Cubes", latex: "a^3 + b^3 = (a+b)(a^2 - ab + b^2)", description: "Factorising sum of cubes" },
    { name: "Difference of Cubes", latex: "a^3 - b^3 = (a-b)(a^2 + ab + b^2)", description: "Factorising difference of cubes" },
    { name: "Discriminant", latex: "\\Delta = b^2 - 4ac", description: "Determines nature of quadratic roots" },
    { name: "Vertex Form", latex: "y = a(x-h)^2 + k", description: "Parabola with vertex at (h, k)" },
    { name: "Logarithm Definition", latex: "\\log_a b = c \\iff a^c = b", description: "Relationship between log and exponent" },
    { name: "Log Product Rule", latex: "\\log_a(xy) = \\log_a x + \\log_a y", description: "Log of a product" },
    { name: "Log Quotient Rule", latex: "\\log_a\\!\\left(\\dfrac{x}{y}\\right) = \\log_a x - \\log_a y", description: "Log of a quotient" },
    { name: "Log Power Rule", latex: "\\log_a(x^n) = n\\log_a x", description: "Log of a power" },
    { name: "Change of Base", latex: "\\log_a b = \\dfrac{\\ln b}{\\ln a}", description: "Convert between log bases" },
    { name: "Binomial Theorem", latex: "(a+b)^n = \\sum_{k=0}^{n}\\binom{n}{k}a^{n-k}b^k", description: "Expansion of a binomial power" },
    { name: "Partial Fractions (distinct linear)", latex: "\\dfrac{A}{x-a} + \\dfrac{B}{x-b}", description: "Decompose rational expression" },
    { name: "Remainder Theorem", latex: "f(a) = \\text{remainder when } f(x) \\div (x-a)", description: "Find remainder without long division" },
    { name: "Factor Theorem", latex: "(x-a) \\text{ is a factor} \\iff f(a)=0", description: "Root ↔ factor equivalence" },
    { name: "Exponential Growth/Decay", latex: "A = A_0\\,e^{kt}", description: "k > 0 = growth; k < 0 = decay" },
    { name: "Vieta's Formulas (quadratic)", latex: "\\alpha+\\beta = -\\dfrac{b}{a},\\quad \\alpha\\beta = \\dfrac{c}{a}", description: "Sum and product of roots" },
    { name: "AM–GM Inequality", latex: "\\dfrac{a+b}{2} \\geq \\sqrt{ab}", description: "Arithmetic mean ≥ geometric mean" },
      { name: "Absolute Value Definition", latex: "|x| = \\begin{cases} x & x\\geq 0 \\\\ -x & x<0 \\end{cases}", description: "Piecewise definition of absolute value" },
    { name: "Binomial Coefficient", latex: "\\binom{n}{k} = \\dfrac{n!}{k!(n-k)!}", description: "Number of ways to choose k from n" },
    { name: "Ceiling Function", latex: "\\lceil x \\rceil = \\text{least integer} \\geq x", description: "Round up to nearest integer" },
    { name: "Floor Function", latex: "\\lfloor x \\rfloor = \\text{greatest integer} \\leq x", description: "Round down to nearest integer" },
    { name: "Natural Exponential Limit", latex: "e = \\lim_{n\\to\\infty}\\left(1+\\dfrac{1}{n}\\right)^n", description: "Definition of Euler's number" },
    { name: "Partial Fractions (repeated linear)", latex: "\\dfrac{A}{x-a} + \\dfrac{B}{(x-a)^2}", description: "Repeated linear factor decomposition" },
    { name: "Rational Root Theorem", latex: "\\text{possible roots} = \\pm\\dfrac{\\text{factors of constant}}{\\text{factors of leading coeff}}", description: "Lists candidates for rational roots" },
    { name: "Vieta's Formulas (cubic)", latex: "\\alpha+\\beta+\\gamma = -\\dfrac{b}{a},\\quad \\alpha\\beta\\gamma = -\\dfrac{d}{a}", description: "Root relationships for ax³+bx²+cx+d=0" },
  ]),
  cat("Calculus", [
    { name: "Power Rule (Differentiation)", latex: "\\dfrac{d}{dx}[x^n] = nx^{n-1}", description: "Derivative of a power function" },
    { name: "Power Rule (Integration)", latex: "\\int x^n\\,dx = \\dfrac{x^{n+1}}{n+1} + C", description: "Antiderivative of a power function" },
    { name: "Chain Rule", latex: "\\dfrac{dy}{dx} = \\dfrac{dy}{du}\\cdot\\dfrac{du}{dx}", description: "Derivative of composite functions" },
    { name: "Product Rule", latex: "\\dfrac{d}{dx}[uv] = u'v + uv'", description: "Derivative of a product" },
    { name: "Quotient Rule", latex: "\\dfrac{d}{dx}\\!\\left[\\dfrac{u}{v}\\right] = \\dfrac{u'v - uv'}{v^2}", description: "Derivative of a quotient" },
    { name: "Derivative of sin", latex: "\\dfrac{d}{dx}[\\sin x] = \\cos x", description: "Trig derivative" },
    { name: "Derivative of cos", latex: "\\dfrac{d}{dx}[\\cos x] = -\\sin x", description: "Trig derivative" },
    { name: "Derivative of tan", latex: "\\dfrac{d}{dx}[\\tan x] = \\sec^2 x", description: "Trig derivative" },
    { name: "Derivative of eˣ", latex: "\\dfrac{d}{dx}[e^x] = e^x", description: "Exponential derivative" },
    { name: "Derivative of ln x", latex: "\\dfrac{d}{dx}[\\ln x] = \\dfrac{1}{x}", description: "Natural log derivative" },
    { name: "Definite Integral", latex: "\\int_a^b f(x)\\,dx = F(b) - F(a)", description: "Fundamental Theorem of Calculus" },
    { name: "Integration by Parts", latex: "\\int u\\,dv = uv - \\int v\\,du", description: "Integral analogue of product rule" },
    { name: "Integration by Substitution", latex: "\\int f(g(x))g'(x)\\,dx = \\int f(u)\\,du", description: "u-substitution technique" },
    { name: "Area Between Curves", latex: "A = \\int_a^b [f(x) - g(x)]\\,dx", description: "Area between two functions" },
    { name: "Volume of Revolution (disk)", latex: "V = \\pi\\int_a^b [f(x)]^2\\,dx", description: "Rotate y = f(x) about x-axis" },
    { name: "Trapezoidal Rule", latex: "\\int_a^b f(x)\\,dx \\approx \\dfrac{h}{2}[f(a)+2f(x_1)+\\cdots+f(b)]", description: "Numerical integration approximation" },
    { name: "L'Hôpital's Rule", latex: "\\lim_{x\\to a}\\dfrac{f(x)}{g(x)} = \\lim_{x\\to a}\\dfrac{f'(x)}{g'(x)}", description: "For 0/0 or ∞/∞ indeterminate forms" },
    { name: "Taylor Series", latex: "f(x) = \\sum_{n=0}^{\\infty}\\dfrac{f^{(n)}(a)}{n!}(x-a)^n", description: "Infinite polynomial approximation" },
    { name: "Newton's Method", latex: "x_{n+1} = x_n - \\dfrac{f(x_n)}{f'(x_n)}", description: "Iterative root-finding algorithm" },
      { name: "Arc Length", latex: "L = \\int_a^b \\sqrt{1+[f\'(x)]^2}\\,dx", description: "Length of a curve" },
    { name: "Derivative of arccos", latex: "\\dfrac{d}{dx}[\\arccos x] = \\dfrac{-1}{\\sqrt{1-x^2}}", description: "Inverse trig derivative" },
    { name: "Derivative of arcsin", latex: "\\dfrac{d}{dx}[\\arcsin x] = \\dfrac{1}{\\sqrt{1-x^2}}", description: "Inverse trig derivative" },
    { name: "Derivative of arctan", latex: "\\dfrac{d}{dx}[\\arctan x] = \\dfrac{1}{1+x^2}", description: "Inverse trig derivative" },
    { name: "Derivative of aˣ", latex: "\\dfrac{d}{dx}[a^x] = a^x\\ln a", description: "Generalised exponential derivative" },
    { name: "Improper Integral", latex: "\\int_a^{\\infty} f(x)\\,dx = \\lim_{t\\to\\infty}\\int_a^t f(x)\\,dx", description: "Integral over unbounded interval" },
    { name: "Inflection Point Condition", latex: "f\'\'(c) = 0 \\text{ and sign of } f\'\' \\text{ changes}", description: "Point where concavity changes" },
    { name: "Integral of 1/x", latex: "\\int \\dfrac{1}{x}\\,dx = \\ln|x| + C", description: "Integral of reciprocal" },
    { name: "Integral of cos", latex: "\\int \\cos x\\,dx = \\sin x + C", description: "Trig integral" },
    { name: "Integral of eˣ", latex: "\\int e^x\\,dx = e^x + C", description: "Exponential integral" },
    { name: "Integral of sec²", latex: "\\int \\sec^2 x\\,dx = \\tan x + C", description: "Standard trig integral" },
    { name: "Integral of sin", latex: "\\int \\sin x\\,dx = -\\cos x + C", description: "Trig integral" },
    { name: "Integral of tan", latex: "\\int \\tan x\\,dx = -\\ln|\\cos x| + C", description: "Standard trig integral" },
    { name: "Integral: 1/(1+x²)", latex: "\\int \\dfrac{1}{1+x^2}\\,dx = \\arctan x + C", description: "Inverse trig integral" },
    { name: "Integral: 1/√(1−x²)", latex: "\\int \\dfrac{1}{\\sqrt{1-x^2}}\\,dx = \\arcsin x + C", description: "Inverse trig integral" },
    { name: "Limit Definition of Derivative", latex: "f\'(x) = \\lim_{h\\to 0}\\dfrac{f(x+h)-f(x)}{h}", description: "First principles definition" },
    { name: "Mean Value Theorem", latex: "f\'(c) = \\dfrac{f(b)-f(a)}{b-a}", description: "Some c exists where derivative equals average rate" },
    { name: "Second Derivative Test", latex: "f\'\'(c)>0 \\Rightarrow \\text{min};\\quad f\'\'(c)<0 \\Rightarrow \\text{max}", description: "Nature of a stationary point" },
    { name: "Taylor Series (general)", latex: "f(x) = \\sum_{n=0}^{\\infty}\\dfrac{f^{(n)}(a)}{n!}(x-a)^n", description: "Infinite polynomial approximation around x=a" },
  ]),
  cat("Trigonometry", [
    { name: "Sine", latex: "\\sin \\theta = \\dfrac{\\text{Opposite}}{\\text{Hypotenuse}}", description: "Relates sides and angles of a triangle" },
    { name: "Cosine", latex: "\\cos \\theta = \\dfrac{\\text{Adjacent}}{\\text{Hypotenuse}}", description: "Relates sides and angles of a triangle" },
    { name: "Tangent", latex: "\\tan \\theta = \\dfrac{\\text{Opposite}}{\\text{Adjacent}}", description: "Relates sides and angles of a triangle" },
    { name: "Sine Rule", latex: "\\dfrac{a}{\\sin A} = \\dfrac{b}{\\sin B} = \\dfrac{c}{\\sin C}", description: "Relates sides and angles of any triangle" },
    { name: "Cosine Rule", latex: "c^2 = a^2 + b^2 - 2ab\\cos C", description: "Generalisation of Pythagoras" },
    { name: "Area of a Triangle", latex: "A = \\dfrac{1}{2}ab\\sin C", description: "When two sides and included angle are known" },
    { name: "Pythagorean Identity", latex: "\\sin^2\\theta + \\cos^2\\theta = 1", description: "Fundamental trig identity" },
    { name: "Double Angle (sin)", latex: "\\sin 2\\theta = 2\\sin\\theta\\cos\\theta", description: "Double angle formula" },
    { name: "Double Angle (cos)", latex: "\\cos 2\\theta = \\cos^2\\theta - \\sin^2\\theta", description: "Double angle formula" },
    { name: "Compound Angle (sin)", latex: "\\sin(A\\pm B) = \\sin A\\cos B \\pm \\cos A\\sin B", description: "Addition formula" },
    { name: "Compound Angle (cos)", latex: "\\cos(A\\pm B) = \\cos A\\cos B \\mp \\sin A\\sin B", description: "Addition formula" },
    { name: "Arc Length", latex: "l = r\\theta", description: "Arc length where θ is in radians" },
    { name: "Sector Area", latex: "A = \\dfrac{1}{2}r^2\\theta", description: "Area of a sector" },
    { name: "Radians to Degrees", latex: "\\theta_{\\deg} = \\theta_{\\text{rad}} \\times \\dfrac{180}{\\pi}", description: "Unit conversion" },
      { name: "Compound Angle (tan)", latex: "\\tan(A\\pm B) = \\dfrac{\\tan A \\pm \\tan B}{1\\mp\\tan A\\tan B}", description: "Addition formula for tan" },
    { name: "Cosec Identity", latex: "1 + \\cot^2\\theta = \\cosec^2\\theta", description: "Pythagorean identity variant" },
    { name: "Degrees → Radians", latex: "\\theta_{\\text{rad}} = \\theta_{\\deg} \\times \\dfrac{\\pi}{180}", description: "Degrees to radians conversion" },
    { name: "Double Angle (cos alt 1)", latex: "\\cos 2\\theta = 2\\cos^2\\theta - 1", description: "Double angle formula variant" },
    { name: "Double Angle (cos alt 2)", latex: "\\cos 2\\theta = 1 - 2\\sin^2\\theta", description: "Double angle formula variant" },
    { name: "Double Angle (tan)", latex: "\\tan 2\\theta = \\dfrac{2\\tan\\theta}{1-\\tan^2\\theta}", description: "Double angle for tan" },
    { name: "Exact value: sin 30°", latex: "\\sin 30^\\circ = \\sin\\tfrac{\\pi}{6} = \\tfrac{1}{2}", description: "Exact trigonometric value" },
    { name: "Exact value: sin 45°", latex: "\\sin 45^\\circ = \\dfrac{\\sqrt{2}}{2}", description: "Exact trigonometric value" },
    { name: "Exact value: sin 60°", latex: "\\sin 60^\\circ = \\dfrac{\\sqrt{3}}{2}", description: "Exact trigonometric value" },
    { name: "Exact value: tan 45°", latex: "\\tan 45^\\circ = \\tan\\tfrac{\\pi}{4} = 1", description: "Exact trigonometric value" },
    { name: "General Solution (cos)", latex: "\\cos\\theta = k \\Rightarrow \\theta = 2n\\pi \\pm \\arccos k", description: "All solutions to cos θ = k" },
    { name: "General Solution (sin)", latex: "\\sin\\theta = k \\Rightarrow \\theta = n\\pi + (-1)^n\\arcsin k", description: "All solutions to sin θ = k" },
    { name: "General Solution (tan)", latex: "\\tan\\theta = k \\Rightarrow \\theta = n\\pi + \\arctan k", description: "All solutions to tan θ = k" },
    { name: "Half Angle (cos)", latex: "\\cos\\tfrac{\\theta}{2} = \\pm\\sqrt{\\dfrac{1+\\cos\\theta}{2}}", description: "Half angle formula" },
    { name: "Half Angle (sin)", latex: "\\sin\\tfrac{\\theta}{2} = \\pm\\sqrt{\\dfrac{1-\\cos\\theta}{2}}", description: "Half angle formula" },
    { name: "Inverse cos domain", latex: "\\arccos: [-1,1]\\to[0,\\pi]", description: "Domain and range of arccos" },
    { name: "Inverse sin domain", latex: "\\arcsin: [-1,1]\\to[-\\tfrac{\\pi}{2},\\tfrac{\\pi}{2}]", description: "Domain and range of arcsin" },
    { name: "Inverse tan domain", latex: "\\arctan: \\mathbb{R}\\to(-\\tfrac{\\pi}{2},\\tfrac{\\pi}{2})", description: "Domain and range of arctan" },
    { name: "Product-to-Sum (sin·cos)", latex: "\\sin A\\cos B = \\tfrac{1}{2}[\\sin(A+B)+\\sin(A-B)]", description: "Product to sum identity" },
    { name: "Sec Identity", latex: "1 + \\tan^2\\theta = \\sec^2\\theta", description: "Pythagorean identity variant" },
    { name: "Sum-to-Product (sin+sin)", latex: "\\sin A+\\sin B = 2\\sin\\tfrac{A+B}{2}\\cos\\tfrac{A-B}{2}", description: "Sum to product identity" },
    { name: "Tan Identity", latex: "\\tan\\theta = \\dfrac{\\sin\\theta}{\\cos\\theta}", description: "Definition of tangent" },
  ]),
  cat("Statistics & Probability", [
    { name: "Mean", latex: "\\bar{x} = \\dfrac{\\sum x_i}{n}", description: "Average of a data set" },
    { name: "Standard Deviation (sample)", latex: "s = \\sqrt{\\dfrac{\\sum(x_i - \\bar{x})^2}{n-1}}", description: "Spread of data around the mean" },
    { name: "z-score", latex: "z = \\dfrac{x - \\mu}{\\sigma}", description: "Standardised value" },
    { name: "Correlation Coefficient", latex: "r = \\dfrac{\\sum(x_i-\\bar{x})(y_i-\\bar{y})}{\\sqrt{\\sum(x_i-\\bar{x})^2\\sum(y_i-\\bar{y})^2}}", description: "Pearson's r" },
    { name: "Probability", latex: "P(A) = \\dfrac{\\text{favourable outcomes}}{\\text{total outcomes}}", description: "Basic probability" },
    { name: "Complementary Events", latex: "P(A') = 1 - P(A)", description: "Probability of the complement" },
    { name: "Addition Rule", latex: "P(A\\cup B) = P(A)+P(B)-P(A\\cap B)", description: "Probability of A or B" },
    { name: "Conditional Probability", latex: "P(A|B) = \\dfrac{P(A\\cap B)}{P(B)}", description: "Probability of A given B" },
    { name: "Binomial Probability", latex: "P(X=k) = \\binom{n}{k}p^k(1-p)^{n-k}", description: "Exactly k successes in n trials" },
    { name: "Bayes' Theorem", latex: "P(A|B) = \\dfrac{P(B|A)P(A)}{P(B)}", description: "Update probability with new evidence" },
    { name: "Normal Distribution PDF", latex: "f(x) = \\dfrac{1}{\\sigma\\sqrt{2\\pi}}e^{-\\frac{1}{2}\\left(\\frac{x-\\mu}{\\sigma}\\right)^2}", description: "Bell curve probability density" },
    { name: "68–95–99.7 Rule", latex: "P(\\mu\\pm\\sigma)\\approx68\\%,\\; P(\\mu\\pm2\\sigma)\\approx95\\%,\\; P(\\mu\\pm3\\sigma)\\approx99.7\\%", description: "Empirical rule for normal distribution" },
      { name: "Coefficient of Variation", latex: "CV = \\dfrac{\\sigma}{\\mu}\\times 100\\%", description: "Relative measure of spread" },
    { name: "Combinations", latex: "^nC_r = \\dfrac{n!}{r!(n-r)!}", description: "Unordered selections of r from n" },
    { name: "Expected Value", latex: "E(X) = \\sum x_i\\,P(X=x_i)", description: "Mean of a discrete random variable" },
    { name: "Geometric Distribution (PMF)", latex: "P(X=k) = (1-p)^{k-1}p", description: "First success on kth trial" },
    { name: "Interquartile Range", latex: "IQR = Q_3 - Q_1", description: "Spread of the middle 50% of data" },
    { name: "Law of Total Probability", latex: "P(B) = \\sum_i P(B|A_i)P(A_i)", description: "Partition sample space to find P(B)" },
    { name: "Multiplication Rule (independent)", latex: "P(A\\cap B) = P(A)\\cdot P(B)", description: "Probability of A and B (independent)" },
    { name: "Outlier Fence (lower)", latex: "Q_1 - 1.5\\times IQR", description: "Values below this are outliers" },
    { name: "Outlier Fence (upper)", latex: "Q_3 + 1.5\\times IQR", description: "Values above this are outliers" },
    { name: "Permutations", latex: "^nP_r = \\dfrac{n!}{(n-r)!}", description: "Ordered arrangements of r from n" },
    { name: "Poisson Distribution (PMF)", latex: "P(X=k) = \\dfrac{\\lambda^k e^{-\\lambda}}{k!}", description: "Events in fixed interval, mean λ" },
    { name: "Regression Intercept", latex: "b_0 = \\bar{y} - b_1\\bar{x}", description: "y-intercept of regression line" },
    { name: "Regression Slope", latex: "b_1 = r\\dfrac{s_y}{s_x}", description: "Slope using correlation and standard deviations" },
    { name: "Standard Deviation (population)", latex: "\\sigma = \\sqrt{\\dfrac{\\sum(x_i - \\mu)^2}{N}}", description: "Population spread" },
    { name: "Variance", latex: "\\text{Var}(X) = E(X^2) - [E(X)]^2", description: "Spread of a random variable" },
  ]),
  cat("Sequences & Series", [
    { name: "Arithmetic nth Term", latex: "T_n = a + (n-1)d", description: "a = first term, d = common difference" },
    { name: "Geometric nth Term", latex: "T_n = ar^{n-1}", description: "a = first term, r = common ratio" },
    { name: "Sum of Arithmetic Series", latex: "S_n = \\dfrac{n}{2}(2a + (n-1)d)", description: "Sum of first n terms" },
    { name: "Sum of Geometric Series", latex: "S_n = \\dfrac{a(1-r^n)}{1-r}", description: "Sum of first n terms (r ≠ 1)" },
    { name: "Sum to Infinity", latex: "S_\\infty = \\dfrac{a}{1-r},\\quad |r|<1", description: "Infinite geometric series" },
      { name: "Arithmetic Mean", latex: "\\bar{x} = \\dfrac{a+b}{2}", description: "Arithmetic mean of two terms" },
    { name: "Arithmetic Series (alt form)", latex: "S_n = \\dfrac{n}{2}(a+l)", description: "a = first term, l = last term" },
    { name: "Geometric Mean", latex: "g = \\sqrt{ab}", description: "Geometric mean of two terms" },
    { name: "Sigma Notation", latex: "\\sum_{k=1}^{n}k = \\dfrac{n(n+1)}{2}", description: "Sum of first n natural numbers" },
    { name: "Sum of Cubes (formula)", latex: "\\sum_{k=1}^{n}k^3 = \\left(\\dfrac{n(n+1)}{2}\\right)^2", description: "Sum of first n cubes" },
    { name: "Sum of Squares", latex: "\\sum_{k=1}^{n}k^2 = \\dfrac{n(n+1)(2n+1)}{6}", description: "Sum of first n perfect squares" },
    { name: "Sum to Infinity (Geometric)", latex: "S_\\infty = \\dfrac{a}{1-r},\\quad |r|<1", description: "Infinite geometric series" },
    { name: "Telescoping Sum", latex: "\\sum_{k=1}^{n}(a_{k+1}-a_k) = a_{n+1}-a_1", description: "Most terms cancel in a telescoping series" },
  ]),
  cat("Vectors", [
    { name: "Vector Magnitude (2D)", latex: "|\\mathbf{a}| = \\sqrt{a_x^2 + a_y^2}", description: "Length of a 2D vector" },
    { name: "Dot Product", latex: "\\mathbf{a}\\cdot\\mathbf{b} = |\\mathbf{a}||\\mathbf{b}|\\cos\\theta", description: "Scalar product" },
    { name: "Angle Between Vectors", latex: "\\cos\\theta = \\dfrac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{a}||\\mathbf{b}|}", description: "Find angle using dot product" },
    { name: "Vector Equation of Line", latex: "\\mathbf{r} = \\mathbf{a} + t\\mathbf{d}", description: "Point a + scalar t × direction d" },
      { name: "Cross Product Magnitude", latex: "|\\mathbf{a}\\times\\mathbf{b}| = |\\mathbf{a}||\\mathbf{b}|\\sin\\theta", description: "Area of parallelogram spanned by a and b" },
    { name: "Parallel Vectors", latex: "\\mathbf{a}\\parallel\\mathbf{b} \\iff \\mathbf{a} = k\\mathbf{b}", description: "One is a scalar multiple of the other" },
    { name: "Perpendicular Vectors", latex: "\\mathbf{a}\\perp\\mathbf{b} \\iff \\mathbf{a}\\cdot\\mathbf{b}=0", description: "Dot product = 0 means perpendicular" },
    { name: "Unit Vector", latex: "\\hat{\\mathbf{a}} = \\dfrac{\\mathbf{a}}{|\\mathbf{a}|}", description: "Vector of length 1 in direction of a" },
    { name: "Vector Magnitude (3D)", latex: "|\\mathbf{a}| = \\sqrt{a_x^2 + a_y^2 + a_z^2}", description: "Length of a 3D vector" },
    { name: "Vector Projection", latex: "\\text{proj}_{\\mathbf{b}}\\mathbf{a} = \\dfrac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{b}|^2}\\mathbf{b}", description: "Component of a along b" },
  ]),
  cat("Geometry", [
    { name: "Pythagoras' Theorem", latex: "c^2 = a^2 + b^2", description: "Right-angled triangle side lengths" },
    { name: "Circle Area", latex: "A = \\pi r^2", description: "Area of a circle" },
    { name: "Circle Circumference", latex: "C = 2\\pi r", description: "Perimeter of a circle" },
    { name: "Sphere Volume", latex: "V = \\dfrac{4}{3}\\pi r^3", description: "Volume of a sphere" },
    { name: "Cylinder Volume", latex: "V = \\pi r^2 h", description: "Volume of a cylinder" },
    { name: "Cone Volume", latex: "V = \\dfrac{1}{3}\\pi r^2 h", description: "Volume of a cone" },
    { name: "Distance Formula", latex: "d = \\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}", description: "Distance between two points" },
    { name: "Midpoint Formula", latex: "M = \\left(\\dfrac{x_1+x_2}{2},\\dfrac{y_1+y_2}{2}\\right)", description: "Midpoint between two points" },
    { name: "Gradient-Intercept Form", latex: "y = mx + b", description: "Equation of a straight line" },
      { name: "Cone Surface Area", latex: "SA = \\pi r^2 + \\pi r l", description: "l = slant height" },
    { name: "Cylinder Surface Area", latex: "SA = 2\\pi r^2 + 2\\pi rh", description: "Two circles + lateral surface" },
    { name: "Each Interior Angle (regular)", latex: "\\theta = \\dfrac{(n-2)\\times 180^\\circ}{n}", description: "Each angle of a regular n-gon" },
    { name: "Euler's Formula (polyhedra)", latex: "V - E + F = 2", description: "Vertices − Edges + Faces = 2 for convex polyhedra" },
    { name: "Gradient of a Line", latex: "m = \\dfrac{y_2-y_1}{x_2-x_1}", description: "Slope between two points" },
    { name: "Heron's Formula", latex: "A = \\sqrt{s(s-a)(s-b)(s-c)},\\quad s=\\tfrac{a+b+c}{2}", description: "Triangle area from three sides" },
    { name: "Inscribed Angle Theorem", latex: "\\text{inscribed angle} = \\tfrac{1}{2}\\times\\text{central angle}", description: "Angle at circumference = half angle at centre" },
    { name: "Interior Angle Sum (polygon)", latex: "S = (n-2)\\times 180^\\circ", description: "n = number of sides" },
    { name: "Point-Gradient Form", latex: "y - y_1 = m(x - x_1)", description: "Line through a point with known gradient" },
    { name: "Power of a Point", latex: "PA\\cdot PB = PC\\cdot PD", description: "For two chords/secants through point P" },
    { name: "Pyramid Volume", latex: "V = \\dfrac{1}{3}A_b h", description: "A_b = base area, h = perpendicular height" },
    { name: "Sphere Surface Area", latex: "SA = 4\\pi r^2", description: "Surface area of a sphere" },
    { name: "Tangent–Radius Angle", latex: "\\text{tangent} \\perp \\text{radius at point of contact}", description: "The tangent to a circle is perpendicular to the radius" },
    { name: "Trapezium Area", latex: "A = \\dfrac{1}{2}(a+b)h", description: "Area of a trapezium" },
  ]),
  cat("Finance", [
    { name: "Compound Interest", latex: "A = P\\!\\left(1+\\dfrac{r}{n}\\right)^{nt}", description: "A = final amount, P = principal" },
    { name: "Simple Interest", latex: "I = Prt", description: "Interest = principal × rate × time" },
    { name: "Present Value", latex: "PV = \\dfrac{FV}{(1+r)^n}", description: "Present value of a future amount" },
      { name: "Depreciation (reducing balance)", latex: "V = P(1-r)^n", description: "Value after n periods at rate r" },
    { name: "Depreciation (straight-line)", latex: "V = P - Dnt", description: "P = purchase price, D = depreciation per period" },
    { name: "Future Value (annuity)", latex: "FV = M\\cdot\\dfrac{(1+r)^n - 1}{r}", description: "Future value of regular payments M" },
  ]),
  cat("Complex Numbers", [
    { name: "Imaginary Unit", latex: "i^2 = -1", description: "Definition of the imaginary unit" },
    { name: "Euler's Formula", latex: "e^{i\\theta} = \\cos\\theta + i\\sin\\theta", description: "Links e, trig and complex numbers" },
    { name: "de Moivre's Theorem", latex: "(r(\\cos\\theta+i\\sin\\theta))^n = r^n(\\cos n\\theta + i\\sin n\\theta)", description: "Powers of complex numbers" },
      { name: "Argument", latex: "\\arg(z) = \\theta = \\arctan\\left(\\dfrac{b}{a}\\right)", description: "Angle from positive real axis" },
    { name: "Complex Conjugate", latex: "\\bar{z} = a - bi", description: "Reflect in real axis" },
    { name: "Complex Number", latex: "z = a + bi,\\quad a,b\\in\\mathbb{R}", description: "Real part a, imaginary part b" },
    { name: "Euler's Identity", latex: "e^{i\\pi} + 1 = 0", description: "Famous special case of Euler's formula" },
    { name: "Modulus", latex: "|z| = \\sqrt{a^2+b^2}", description: "Distance from origin in Argand plane" },
    { name: "Polar Form", latex: "z = r(\\cos\\theta + i\\sin\\theta) = re^{i\\theta}", description: "Modulus-argument form" },
    { name: "nth Roots of Unity", latex: "z^n = 1 \\Rightarrow z = e^{2\\pi ki/n},\\; k=0,1,\\ldots,n-1", description: "n equally-spaced roots on unit circle" },
  ]),
  cat("Matrices", [
    { name: "Determinant (2×2)", latex: "\\det\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix} = ad - bc", description: "Determinant of a 2×2 matrix" },
    { name: "Inverse (2×2)", latex: "A^{-1} = \\dfrac{1}{ad-bc}\\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix}", description: "Inverse of a 2×2 matrix" },
      { name: "Characteristic Equation", latex: "\\det(A - \\lambda I) = 0", description: "Find eigenvalues" },
    { name: "Eigenvalue Equation", latex: "A\\mathbf{v} = \\lambda\\mathbf{v}", description: "λ = eigenvalue, v = eigenvector" },
    { name: "Inverse Property", latex: "AA^{-1} = A^{-1}A = I", description: "Product with inverse gives identity" },
    { name: "Systems via Matrices", latex: "A\\mathbf{x} = \\mathbf{b} \\Rightarrow \\mathbf{x} = A^{-1}\\mathbf{b}", description: "Solve linear system using inverse" },
  ]),
  cat("Functions & Graphs", [
    { name: "Even Function", latex: "f(-x) = f(x)", description: "Symmetric about y-axis" },
    { name: "Odd Function", latex: "f(-x) = -f(x)", description: "Symmetric about origin" },
    { name: "Composite Function", latex: "(f \\circ g)(x) = f(g(x))", description: "Apply g first, then f" },
    { name: "Equation of a Circle", latex: "(x-h)^2 + (y-k)^2 = r^2", description: "Circle with centre (h,k) and radius r" },
      { name: "Absolute Value Function", latex: "f(x) = |x| = \\sqrt{x^2}", description: "V-shaped graph, vertex at origin" },
    { name: "Asymptote: Oblique", latex: "y = mx+b \\text{ when } \\lim_{x\\to\\infty}[f(x)-(mx+b)]=0", description: "Slant asymptote of a rational function" },
    { name: "Inverse Function Notation", latex: "f^{-1}(y) = x \\iff f(x) = y", description: "Swap x and y to find inverse" },
    { name: "Logistic Function", latex: "f(x) = \\dfrac{L}{1+e^{-k(x-x_0)}}", description: "S-curve, max value L" },
    { name: "Sinusoidal Model", latex: "y = A\\sin(Bx + C) + D", description: "A=amplitude, 2π/B=period, C=phase shift, D=vertical shift" },
  ]),
  cat("Number Theory & Proof", [
    { name: "GCD (Euclidean)", latex: "\\gcd(a,b) = \\gcd(b,\\, a\\bmod b)", description: "Euclidean algorithm for GCD" },
    { name: "Mathematical Induction", latex: "P(1)\\text{ true, }P(k)\\Rightarrow P(k+1) \\Rightarrow P(n)\\text{ for all }n\\in\\mathbb{N}", description: "Proof technique" },
      { name: "Division Algorithm", latex: "a = bq + r,\\quad 0 \\leq r < b", description: "Divides a by b with remainder r" },
    { name: "LCM from GCD", latex: "\\text{lcm}(a,b) = \\dfrac{|ab|}{\\gcd(a,b)}", description: "Lowest common multiple" },
    { name: "Modular Arithmetic", latex: "a \\equiv b \\pmod{m} \\iff m\\mid(a-b)", description: "a and b have same remainder mod m" },
  ]),
  cat("Coordinate Geometry", [
    { name: "Angle of Inclination", latex: "m = \\tan\\theta", description: "Gradient = tan of angle with positive x-axis" },
    { name: "Area of Triangle (coordinates)", latex: "A = \\dfrac{1}{2}|x_1(y_2-y_3)+x_2(y_3-y_1)+x_3(y_1-y_2)|", description: "Using vertex coordinates" },
    { name: "Distance from Point to Line", latex: "d = \\dfrac{|ax_0+by_0+c|}{\\sqrt{a^2+b^2}}", description: "Distance from (x₀,y₀) to line ax+by+c=0" },
    { name: "Division of Line Segment", latex: "P = \\left(\\dfrac{mx_2+nx_1}{m+n},\\dfrac{my_2+ny_1}{m+n}\\right)", description: "Point dividing AB in ratio m:n" },
    { name: "Ellipse (standard)", latex: "\\dfrac{x^2}{a^2}+\\dfrac{y^2}{b^2}=1", description: "Ellipse centred at origin, semi-axes a, b" },
    { name: "Equation of a Circle", latex: "(x-h)^2 + (y-k)^2 = r^2", description: "Circle with centre (h,k) and radius r" },
    { name: "General Circle Equation", latex: "x^2 + y^2 + Dx + Ey + F = 0", description: "Complete the square to find centre/radius" },
    { name: "Hyperbola (standard)", latex: "\\dfrac{x^2}{a^2}-\\dfrac{y^2}{b^2}=1", description: "Hyperbola opening left/right" },
    { name: "Parabola (vertical)", latex: "x^2 = 4py", description: "Vertex at origin, focus at (0,p)" },
    { name: "Perpendicular Gradient", latex: "m_1 \\times m_2 = -1", description: "Gradients of perpendicular lines multiply to −1" },
  ])
];

const PHYSICS_CATEGORIES = [
  cat("Kinematics", [
    { name: "v = u + at", latex: "v = u + at", description: "Final velocity with constant acceleration" },
    { name: "s = ut + ½at²", latex: "s = ut + \\tfrac{1}{2}at^2", description: "Displacement with constant acceleration" },
    { name: "v² = u² + 2as", latex: "v^2 = u^2 + 2as", description: "Velocity–displacement relation" },
    { name: "s = ½(u+v)t", latex: "s = \\tfrac{1}{2}(u+v)t", description: "Displacement using average velocity" },
    { name: "Projectile Range", latex: "R = \\dfrac{u^2\\sin 2\\theta}{g}", description: "Horizontal range on flat ground" },
    { name: "Projectile Max Height", latex: "H = \\dfrac{u^2\\sin^2\\theta}{2g}", description: "Maximum height of a projectile" },
    { name: "Circular Speed", latex: "v = \\dfrac{2\\pi r}{T}", description: "Speed in uniform circular motion" },
    { name: "Angular Velocity", latex: "\\omega = \\dfrac{2\\pi}{T} = 2\\pi f", description: "Radians per second" },
      { name: "Average Speed", latex: "v_{\\text{avg}} = \\dfrac{\\text{total distance}}{\\text{total time}}", description: "Average speed over a journey" },
  ]),
  cat("Forces", [
    { name: "Newton's Second Law", latex: "F = ma", description: "Net force = mass × acceleration" },
    { name: "Weight", latex: "W = mg", description: "Gravitational force on a mass" },
    { name: "Friction", latex: "f = \\mu N", description: "μ = coefficient of friction, N = normal force" },
    { name: "Centripetal Force", latex: "F_c = \\dfrac{mv^2}{r} = m\\omega^2 r", description: "Force toward centre of circular path" },
    { name: "Momentum", latex: "p = mv", description: "Mass × velocity" },
    { name: "Impulse", latex: "J = F\\Delta t = \\Delta p", description: "Change in momentum" },
    { name: "Conservation of Momentum", latex: "m_1u_1 + m_2u_2 = m_1v_1 + m_2v_2", description: "Total momentum conserved in collisions" },
    { name: "Hooke's Law", latex: "F = -kx", description: "Restoring force in a spring" },
    { name: "Torque", latex: "\\tau = Fr\\sin\\theta", description: "Rotational force (moment)" },
  ]),
  cat("Energy", [
    { name: "Kinetic Energy", latex: "E_k = \\tfrac{1}{2}mv^2", description: "Energy of motion" },
    { name: "Gravitational PE", latex: "E_p = mgh", description: "Energy due to height" },
    { name: "Elastic PE", latex: "E_{sp} = \\tfrac{1}{2}kx^2", description: "Energy stored in a spring" },
    { name: "Work", latex: "W = Fs\\cos\\theta", description: "Force × displacement" },
    { name: "Power", latex: "P = \\dfrac{W}{t} = Fv", description: "Rate of energy transfer" },
    { name: "Efficiency", latex: "\\eta = \\dfrac{P_{\\text{out}}}{P_{\\text{in}}} \\times 100\\%", description: "Useful output / total input" },
    { name: "Conservation of Energy", latex: "E_k + E_p = \\text{constant}", description: "Mechanical energy conserved (no friction)" },
  ]),
  cat("Waves", [
    { name: "Wave Speed", latex: "v = f\\lambda", description: "Speed = frequency × wavelength" },
    { name: "Period & Frequency", latex: "T = \\dfrac{1}{f}", description: "Period = reciprocal of frequency" },
    { name: "Snell's Law", latex: "n_1\\sin\\theta_1 = n_2\\sin\\theta_2", description: "Refraction at a boundary" },
    { name: "Refractive Index", latex: "n = \\dfrac{c}{v}", description: "Speed of light in medium vs vacuum" },
    { name: "Doppler Effect", latex: "f' = f\\dfrac{v \\pm v_o}{v \\mp v_s}", description: "Observed frequency change due to motion" },
    { name: "Decibels", latex: "L = 10\\log_{10}\\!\\left(\\dfrac{I}{I_0}\\right)", description: "Sound level in dB" },
    { name: "Standing Wave (string)", latex: "f_n = \\dfrac{nv}{2L}", description: "nth harmonic of a string" },
      { name: "Doppler Effect (source moving)", latex: "f\' = f\\dfrac{v \\pm v_o}{v \\mp v_s}", description: "Observed frequency change due to motion" },
    { name: "Intensity", latex: "I = \\dfrac{P}{4\\pi r^2}", description: "Intensity of a point source" },
  ]),
  cat("Electricity", [
    { name: "Ohm's Law", latex: "V = IR", description: "Voltage = current × resistance" },
    { name: "Electric Power", latex: "P = VI = I^2R = \\dfrac{V^2}{R}", description: "Power dissipated" },
    { name: "Resistors in Series", latex: "R_T = R_1 + R_2 + \\cdots", description: "Total resistance in series" },
    { name: "Resistors in Parallel", latex: "\\dfrac{1}{R_T} = \\dfrac{1}{R_1}+\\dfrac{1}{R_2}+\\cdots", description: "Total resistance in parallel" },
    { name: "Coulomb's Law", latex: "F = \\dfrac{kq_1q_2}{r^2}", description: "Force between two charges" },
    { name: "Electric Field", latex: "E = \\dfrac{F}{q} = \\dfrac{kQ}{r^2}", description: "Force per unit charge" },
    { name: "Magnetic Force on Wire", latex: "F = BIl\\sin\\theta", description: "Force on a current-carrying wire" },
    { name: "Magnetic Force on Charge", latex: "F = qvB\\sin\\theta", description: "Force on a moving charge" },
    { name: "Faraday's Law (EMF)", latex: "\\mathcal{E} = -N\\dfrac{\\Delta\\Phi}{\\Delta t}", description: "Induced EMF from changing flux" },
    { name: "Transformer Ratio", latex: "\\dfrac{V_s}{V_p} = \\dfrac{N_s}{N_p}", description: "Voltage ratio = turns ratio" },
      { name: "Capacitance", latex: "C = \\dfrac{Q}{V}", description: "Charge stored per unit voltage" },
    { name: "Charge", latex: "Q = It", description: "Charge = current × time" },
    { name: "Energy in Capacitor", latex: "E = \\tfrac{1}{2}CV^2", description: "Energy stored in a capacitor" },
  ]),
  cat("Gravity", [
    { name: "Universal Gravitation", latex: "F = \\dfrac{Gm_1m_2}{r^2}", description: "Force between two masses" },
    { name: "Gravitational Field Strength", latex: "g = \\dfrac{GM}{r^2}", description: "Field strength at distance r" },
    { name: "Orbital Speed", latex: "v = \\sqrt{\\dfrac{GM}{r}}", description: "Speed for circular orbit" },
    { name: "Orbital Period (Kepler III)", latex: "T^2 = \\dfrac{4\\pi^2 r^3}{GM}", description: "Period of a circular orbit" },
    { name: "Escape Velocity", latex: "v_e = \\sqrt{\\dfrac{2GM}{r}}", description: "Minimum speed to escape gravity" },
  ]),
  cat("Thermodynamics", [
    { name: "Specific Heat Capacity", latex: "Q = mc\\Delta T", description: "Heat = mass × specific heat × temperature change" },
    { name: "Latent Heat", latex: "Q = mL", description: "Heat for phase change" },
    { name: "Ideal Gas Law", latex: "PV = nRT", description: "P = pressure, V = volume, n = moles" },
    { name: "First Law of Thermodynamics", latex: "\\Delta U = Q - W", description: "Change in internal energy" },
      { name: "Boyle's Law", latex: "P_1V_1 = P_2V_2", description: "Pressure–volume at constant temperature" },
    { name: "Charles's Law", latex: "\\dfrac{V_1}{T_1} = \\dfrac{V_2}{T_2}", description: "Volume–temperature at constant pressure" },
  ]),
  cat("Nuclear", [
    { name: "Mass-Energy Equivalence", latex: "E = mc^2", description: "Einstein's famous relation" },
    { name: "Radioactive Decay", latex: "N = N_0 e^{-\\lambda t}", description: "Undecayed nuclei at time t" },
    { name: "Half-Life", latex: "t_{1/2} = \\dfrac{\\ln 2}{\\lambda}", description: "Time for half to decay" },
    { name: "Photon Energy", latex: "E = hf = \\dfrac{hc}{\\lambda}", description: "Energy of a photon" },
    { name: "de Broglie Wavelength", latex: "\\lambda = \\dfrac{h}{mv}", description: "Matter wavelength" },
  ]),
];

const CHEMISTRY_CATEGORIES = [
  cat("Stoichiometry", [
    { name: "Moles from Mass", latex: "n = \\dfrac{m}{M}", description: "n = moles, m = mass, M = molar mass" },
    { name: "Concentration", latex: "c = \\dfrac{n}{V}", description: "mol/L, V in litres" },
    { name: "Dilution Formula", latex: "c_1V_1 = c_2V_2", description: "Concentration × volume conserved on dilution" },
    { name: "Percentage Composition", latex: "\\%\\,\\text{element} = \\dfrac{M_{\\text{element}}}{M_{\\text{compound}}}\\times 100", description: "Mass percent of an element" },
    { name: "Percentage Yield", latex: "\\text{yield} = \\dfrac{\\text{actual}}{\\text{theoretical}}\\times 100\\%", description: "Efficiency of a reaction" },
    { name: "Atom Economy", latex: "\\text{atom economy} = \\dfrac{M_{\\text{desired product}}}{M_{\\text{all products}}}\\times 100", description: "Efficiency of a reaction" },
      { name: "Empirical Formula Steps", latex: "\\text{mol ratio} = \\dfrac{\\%/M_{\\text{element}}}{\\text{smallest value}}", description: "Find simplest whole-number ratio" },
    { name: "Moles from Volume (gas, STP)", latex: "n = \\dfrac{V}{22.4}", description: "Volume in litres at STP" },
    { name: "Theoretical Yield", latex: "\\text{yield} = \\dfrac{\\text{actual}}{\\text{theoretical}}\\times 100\\%", description: "Percentage yield of a product" },
  ]),
  cat("Gas Laws", [
    { name: "Ideal Gas Law", latex: "PV = nRT", description: "R = 8.314 J mol⁻¹ K⁻¹" },
    { name: "Dalton's Law", latex: "P_{\\text{total}} = P_1 + P_2 + P_3 + \\cdots", description: "Total pressure = sum of partial pressures" },
    { name: "Graham's Law", latex: "\\dfrac{r_1}{r_2} = \\sqrt{\\dfrac{M_2}{M_1}}", description: "Relative rates of gas effusion" },
      { name: "Boyle's Law", latex: "P_1V_1 = P_2V_2", description: "Constant temperature" },
    { name: "Charles's Law", latex: "\\dfrac{V_1}{T_1} = \\dfrac{V_2}{T_2}", description: "Constant pressure" },
    { name: "Combined Gas Law", latex: "\\dfrac{P_1V_1}{T_1} = \\dfrac{P_2V_2}{T_2}", description: "Combines Boyle's and Charles's laws" },
    { name: "Gay-Lussac's Law", latex: "\\dfrac{P_1}{T_1} = \\dfrac{P_2}{T_2}", description: "Constant volume" },
    { name: "Molar Volume (STP)", latex: "V_m = 22.4\\,\\text{L mol}^{-1}", description: "Volume of 1 mol of gas at STP" },
  ]),
  cat("Acids & Bases", [
    { name: "pH", latex: "\\text{pH} = -\\log_{10}[\\text{H}^+]", description: "Measure of acidity" },
    { name: "pOH", latex: "\\text{pOH} = -\\log_{10}[\\text{OH}^-]", description: "Measure of basicity" },
    { name: "pH + pOH = 14", latex: "\\text{pH} + \\text{pOH} = 14", description: "At 25°C" },
    { name: "Ka Expression", latex: "K_a = \\dfrac{[\\text{H}^+][\\text{A}^-]}{[\\text{HA}]}", description: "Acid dissociation constant" },
    { name: "Henderson-Hasselbalch", latex: "\\text{pH} = pK_a + \\log\\dfrac{[\\text{A}^-]}{[\\text{HA}]}", description: "Buffer pH calculation" },
      { name: "Ka × Kb", latex: "K_a \\times K_b = K_w = 1.0\\times10^{-14}", description: "Conjugate acid-base pair relationship" },
    { name: "Kb Expression", latex: "K_b = \\dfrac{[\\text{BH}^+][\\text{OH}^-]}{[\\text{B}]}", description: "Base dissociation constant" },
    { name: "Neutralisation", latex: "n(\\text{acid}) = n(\\text{base})", description: "At equivalence point" },
  ]),
  cat("Thermochemistry", [
    { name: "Heat of Reaction", latex: "q = mc\\Delta T", description: "Calorimetry calculation" },
    { name: "Enthalpy Change", latex: "\\Delta H = H_{\\text{products}} - H_{\\text{reactants}}", description: "Heat of reaction" },
    { name: "Hess's Law", latex: "\\Delta H_{\\text{rxn}} = \\sum\\Delta H_{\\text{f,products}} - \\sum\\Delta H_{\\text{f,reactants}}", description: "Enthalpy from formation values" },
    { name: "Gibbs Free Energy", latex: "\\Delta G = \\Delta H - T\\Delta S", description: "Spontaneity: ΔG < 0 is spontaneous" },
      { name: "Bond Enthalpy", latex: "\\Delta H = \\sum E_{\\text{broken}} - \\sum E_{\\text{formed}}", description: "Estimate ΔH from bond energies" },
    { name: "Entropy", latex: "\\Delta S = \\dfrac{q_{\\text{rev}}}{T}", description: "Disorder; units J mol⁻¹ K⁻¹" },
  ]),
  cat("Equilibrium", [
    { name: "Equilibrium Constant (Kc)", latex: "K_c = \\dfrac{[C]^c[D]^d}{[A]^a[B]^b}", description: "For aA + bB ⇌ cC + dD" },
    { name: "Reaction Quotient", latex: "Q_c = \\dfrac{[C]^c[D]^d}{[A]^a[B]^b}", description: "Determines direction of shift (Q vs K)" },
    { name: "Solubility Product", latex: "K_{sp} = [\\text{cation}]^m[\\text{anion}]^n", description: "For sparingly soluble salts" },
      { name: "Kp Expression", latex: "K_p = K_c(RT)^{\\Delta n}", description: "Pressure equilibrium constant" },
  ]),
  cat("Electrochemistry", [
    { name: "Faraday's Law", latex: "m = \\dfrac{ItM}{nF}", description: "Mass deposited; F = 96485 C mol⁻¹" },
    { name: "Cell Potential", latex: "E^\\circ_{\\text{cell}} = E^\\circ_{\\text{cathode}} - E^\\circ_{\\text{anode}}", description: "Standard cell voltage" },
    { name: "Nernst Equation", latex: "E = E^\\circ - \\dfrac{RT}{nF}\\ln Q", description: "Cell potential under non-standard conditions" },
      { name: "Charge Carried", latex: "Q = nF", description: "Charge = moles of electrons × Faraday constant" },
    { name: "Gibbs–Cell Potential", latex: "\\Delta G^\\circ = -nFE^\\circ", description: "Links thermodynamics and electrochemistry" },
  ]),
  cat("Reaction Rates", [
    { name: "Rate Expression", latex: "\\text{rate} = k[A]^m[B]^n", description: "k = rate constant, m and n = orders" },
    { name: "Arrhenius Equation", latex: "k = Ae^{-E_a/RT}", description: "Temperature dependence of rate" },
    { name: "Half-Life (first order)", latex: "t_{1/2} = \\dfrac{\\ln 2}{k}", description: "Time for concentration to halve" },
      { name: "Integrated Rate Law (1st order)", latex: "[A]_t = [A]_0 e^{-kt}", description: "Concentration vs time for 1st order" },
    { name: "Integrated Rate Law (2nd order)", latex: "\\dfrac{1}{[A]_t} = \\dfrac{1}{[A]_0} + kt", description: "Concentration vs time for 2nd order" },
  ]),
  cat("Atomic Structure", [
    { name: "Energy of Photon", latex: "E = hf = \\dfrac{hc}{\\lambda}", description: "h = 6.626 × 10⁻³⁴ J·s" },
    { name: "Rydberg Formula", latex: "\\dfrac{1}{\\lambda} = R_H\\!\\left(\\dfrac{1}{n_1^2}-\\dfrac{1}{n_2^2}\\right)", description: "Spectral lines of hydrogen" },
      { name: "Ionisation Energy", latex: "\\text{IE} = -E_n = \\dfrac{13.6\\,\\text{eV}}{n^2}", description: "Energy to remove electron from level n (hydrogen)" },
    { name: "de Broglie Wavelength", latex: "\\lambda = \\dfrac{h}{mv}", description: "Wave-particle duality" },
  ]),
];

const BIOLOGY_CATEGORIES = [
  cat("Genetics", [
    { name: "Hardy-Weinberg (genotypes)", latex: "p^2 + 2pq + q^2 = 1", description: "Genotype frequencies in equilibrium" },
    { name: "Hardy-Weinberg (alleles)", latex: "p + q = 1", description: "Allele frequency sum" },
    { name: "Chi-squared Test", latex: "\\chi^2 = \\sum\\dfrac{(O - E)^2}{E}", description: "Tests if observed ratios fit expected" },
    { name: "Recombination Frequency", latex: "r = \\dfrac{\\text{recombinant offspring}}{\\text{total offspring}}\\times 100\\%", description: "Map units between loci" },
      { name: "Heritability (narrow-sense)", latex: "h^2 = \\dfrac{V_A}{V_P}", description: "Additive genetic variance / phenotypic variance" },
    { name: "Heterozygosity", latex: "H = 2pq", description: "Expected heterozygote frequency" },
    { name: "Number of Gamete Types", latex: "\\text{gamete types} = 2^n", description: "n = number of heterozygous gene pairs" },
  ]),
  cat("Ecology", [
    { name: "Population Growth (exponential)", latex: "\\dfrac{dN}{dt} = rN", description: "r = intrinsic growth rate" },
    { name: "Population Growth (logistic)", latex: "\\dfrac{dN}{dt} = rN\\!\\left(\\dfrac{K-N}{K}\\right)", description: "K = carrying capacity" },
    { name: "Lincoln-Petersen (mark-recapture)", latex: "N = \\dfrac{M \\times C}{R}", description: "M = marked, C = second sample, R = recaptured" },
    { name: "Simpson's Diversity Index", latex: "D = 1 - \\dfrac{\\sum n(n-1)}{N(N-1)}", description: "Measure of species diversity" },
    { name: "Net Primary Productivity", latex: "NPP = GPP - R_a", description: "GPP - autotroph respiration" },
      { name: "Biomass Pyramid", latex: "\\text{biomass}_{n+1} \\approx 0.1 \\times \\text{biomass}_n", description: "Approx 10% rule between trophic levels" },
    { name: "Doubling Time", latex: "t_d = \\dfrac{\\ln 2}{r}", description: "Time for population to double" },
    { name: "Shannon Diversity Index", latex: "H = -\\sum p_i \\ln p_i", description: "pᵢ = proportion of species i" },
    { name: "Trophic Efficiency", latex: "\\text{efficiency} = \\dfrac{E_{n+1}}{E_n}\\times 100\\%", description: "Energy transferred between trophic levels (~10%)" },
  ]),
  cat("Cell Biology", [
    { name: "Surface Area to Volume Ratio", latex: "\\text{SA:V} = \\dfrac{6}{d}", description: "For a cube of side d" },
    { name: "Water Potential", latex: "\\Psi = \\Psi_s + \\Psi_p", description: "Solute + pressure potential" },
    { name: "Mitotic Index", latex: "MI = \\dfrac{\\text{cells in mitosis}}{\\text{total cells}}\\times 100", description: "Proportion of cells dividing" },
      { name: "Cell Cycle Time", latex: "t_{\\text{phase}} = \\dfrac{\\%\\,\\text{cells in phase}}{100} \\times T_{\\text{cycle}}", description: "Time spent in each cell cycle phase" },
    { name: "Fick's Law of Diffusion", latex: "J = -D\\dfrac{\\Delta C}{\\Delta x}", description: "Diffusion rate depends on concentration gradient" },
    { name: "Osmotic Potential", latex: "\\Psi_s = -iCRT", description: "i = van't Hoff factor, C = concentration" },
  ]),
  cat("Photosynthesis & Respiration", [
    { name: "Overall Photosynthesis", latex: "6\\text{CO}_2 + 6\\text{H}_2\\text{O} \\xrightarrow{\\text{light}} \\text{C}_6\\text{H}_{12}\\text{O}_6 + 6\\text{O}_2", description: "Net equation for photosynthesis" },
    { name: "Aerobic Respiration", latex: "\\text{C}_6\\text{H}_{12}\\text{O}_6 + 6\\text{O}_2 \\rightarrow 6\\text{CO}_2 + 6\\text{H}_2\\text{O} + \\text{ATP}", description: "Complete glucose oxidation" },
    { name: "Respiratory Quotient", latex: "RQ = \\dfrac{\\text{CO}_2\\,\\text{produced}}{\\text{O}_2\\,\\text{consumed}}", description: "Indicates substrate being respired" },
      { name: "ATP Yield (glycolysis)", latex: "\\text{glucose} \\rightarrow 2\\,\\text{pyruvate} + 2\\,\\text{ATP} + 2\\,\\text{NADH}", description: "Net ATP from glycolysis" },
    { name: "Anaerobic (ethanol)", latex: "\\text{C}_6\\text{H}_{12}\\text{O}_6 \\rightarrow 2\\,\\text{C}_2\\text{H}_5\\text{OH} + 2\\,\\text{CO}_2 + 2\\,\\text{ATP}", description: "Fermentation in yeast" },
    { name: "Anaerobic (lactic acid)", latex: "\\text{C}_6\\text{H}_{12}\\text{O}_6 \\rightarrow 2\\,\\text{C}_3\\text{H}_6\\text{O}_3 + 2\\,\\text{ATP}", description: "Fermentation in animal muscle" },
    { name: "Calvin Cycle Net", latex: "3\\text{CO}_2 + 9\\text{ATP} + 6\\text{NADPH} \\rightarrow \\text{G3P}", description: "Carbon fixation summary" },
    { name: "Light Reactions", latex: "12\\text{H}_2\\text{O} + \\text{light} \\rightarrow 24\\text{H}^+ + 24e^- + 6\\text{O}_2", description: "Water splitting in thylakoid" },
    { name: "Photosynthetic Rate", latex: "\\text{rate} \\propto \\dfrac{[\\text{CO}_2] \\times \\text{light intensity}}{\\text{temperature factor}}", description: "Limiting factor relationship" },
  ]),
  cat("Evolution", [
    { name: "Relative Fitness", latex: "w = \\dfrac{\\text{survival/reproduction of genotype}}{\\text{max survival/reproduction}}", description: "Fitness relative to most fit" },
    { name: "Selection Coefficient", latex: "s = 1 - w", description: "Disadvantage relative to fittest" },
    { name: "Effective Population Size", latex: "N_e = \\dfrac{4N_f N_m}{N_f + N_m}", description: "Accounts for unequal sex ratios" },
      { name: "Allele Frequency Change", latex: "\\Delta p \\approx \\dfrac{sp^2q}{1-sp^2}", description: "Change in dominant allele frequency per generation" },
  ]),
  cat("Physiology", [
    { name: "Cardiac Output", latex: "CO = HR \\times SV", description: "HR = heart rate, SV = stroke volume" },
    { name: "Mean Arterial Pressure", latex: "MAP = DP + \\dfrac{1}{3}(SP - DP)", description: "DP = diastolic, SP = systolic" },
    { name: "Glomerular Filtration Rate", latex: "GFR = \\dfrac{U \\times V}{P}", description: "U = urine conc, V = urine flow, P = plasma conc" },
    { name: "BMI", latex: "BMI = \\dfrac{m}{h^2}", description: "Body mass (kg) / height² (m²)" },
      { name: "Basal Metabolic Rate (Mifflin–St Jeor, male)", latex: "BMR = 10m + 6.25h - 5a + 5", description: "m = kg, h = cm, a = age" },
    { name: "Haemoglobin O₂ Saturation", latex: "SO_2 = \\dfrac{HbO_2}{Hb_{\\text{total}}}\\times 100\\%", description: "Percentage of haemoglobin carrying oxygen" },
    { name: "Lung Volumes", latex: "VC = TV + IRV + ERV", description: "Vital capacity = tidal + inspiratory reserve + expiratory reserve" },
  ]),
  cat("Molecular Biology", [
    { name: "Chargaff's Rule", latex: "[A]=[T],\\quad [G]=[C]", description: "Base pairing equivalences in dsDNA" },
    { name: "Codon Count", latex: "4^3 = 64\\,\\text{possible codons}", description: "Three-base codons from 4 nucleotides" },
    { name: "DNA Replication Fidelity", latex: "\\text{error rate} \\approx 10^{-9}\\,\\text{errors/base pair}", description: "After proofreading" },
    { name: "Reading Frame", latex: "\\text{ORF length (aa)} = \\dfrac{n - 3}{3}", description: "n = nucleotides; subtract stop codon" },
    { name: "Tm (DNA melting)", latex: "T_m = 81.5 + 16.6\\log[\\text{Na}^+] + 0.41(\\%\\text{GC}) - 675/n", description: "Melting temperature of DNA duplex" },
  ])
];

const ECONOMICS_CATEGORIES = [
  cat("Macroeconomics", [
    { name: "GDP (Expenditure)", latex: "GDP = C + I + G + (X - M)", description: "C=consumption, I=investment, G=govt, X-M=net exports" },
    { name: "Real GDP", latex: "\\text{Real GDP} = \\dfrac{\\text{Nominal GDP}}{\\text{GDP Deflator}}\\times 100", description: "Adjusts for inflation" },
    { name: "Inflation Rate", latex: "\\pi = \\dfrac{\\text{CPI}_{t} - \\text{CPI}_{t-1}}{\\text{CPI}_{t-1}}\\times 100", description: "Percentage change in CPI" },
    { name: "Unemployment Rate", latex: "U = \\dfrac{\\text{Unemployed}}{\\text{Labour force}}\\times 100", description: "Share without work" },
    { name: "Money Multiplier", latex: "m = \\dfrac{1}{\\text{reserve ratio}}", description: "Maximum credit creation" },
    { name: "Quantity Theory of Money", latex: "MV = PQ", description: "M=money supply, V=velocity, P=price, Q=output" },
    { name: "Fiscal Multiplier", latex: "k = \\dfrac{1}{1 - MPC}", description: "MPC = marginal propensity to consume" },
    { name: "Terms of Trade", latex: "ToT = \\dfrac{P_{\\text{exports}}}{P_{\\text{imports}}}\\times 100", description: "Export prices / import prices" },
      { name: "Balanced Budget Multiplier", latex: "k_{BB} = 1", description: "Equal G and T change has multiplier of 1" },
    { name: "CPI", latex: "\\text{CPI} = \\dfrac{\\text{Cost of basket (current)}}{\\text{Cost of basket (base)}}\\times 100", description: "Consumer Price Index" },
    { name: "Current Account Balance", latex: "CA = X - M + NY + NCT", description: "Net exports + net income + net current transfers" },
    { name: "Exchange Rate (direct quote)", latex: "e = \\dfrac{\\text{domestic currency}}{\\text{foreign currency}}", description: "Price of 1 unit of foreign currency in domestic terms" },
    { name: "GDP (Income)", latex: "GDP = W + P + R + I", description: "Wages + Profits + Rent + Interest" },
    { name: "GDP Growth Rate", latex: "g = \\dfrac{GDP_t - GDP_{t-1}}{GDP_{t-1}}\\times 100", description: "Percentage change in GDP" },
    { name: "Labour Force Participation", latex: "LFPR = \\dfrac{\\text{Labour force}}{\\text{Working-age population}}\\times 100", description: "Share of population in labour force" },
    { name: "National Savings", latex: "S = Y - C - G", description: "Output minus consumption minus government spending" },
    { name: "Output Gap", latex: "\\text{Gap} = \\dfrac{Y - Y^*}{Y^*}\\times 100", description: "Actual minus potential GDP as %" },
    { name: "Purchasing Power Parity", latex: "e = \\dfrac{P}{P^*}", description: "Exchange rate that equalises price levels" },
    { name: "Real Exchange Rate", latex: "RER = e \\times \\dfrac{P^*}{P}", description: "Nominal rate adjusted for price levels" },
    { name: "Tax Multiplier", latex: "k_T = \\dfrac{-MPC}{1 - MPC}", description: "Effect of tax change on income" },
  ]),
  cat("Microeconomics", [
    { name: "Price Elasticity of Demand", latex: "PED = \\dfrac{\\%\\Delta Q_d}{\\%\\Delta P}", description: "Responsiveness of Qd to price" },
    { name: "Price Elasticity of Supply", latex: "PES = \\dfrac{\\%\\Delta Q_s}{\\%\\Delta P}", description: "Responsiveness of Qs to price" },
    { name: "Total Revenue", latex: "TR = P \\times Q", description: "Price × quantity" },
    { name: "Profit", latex: "\\pi = TR - TC", description: "Total revenue − total cost" },
    { name: "Profit Maximisation", latex: "MR = MC", description: "Optimal output rule" },
    { name: "Consumer Surplus", latex: "CS = \\dfrac{1}{2}(P_{\\max} - P)\\times Q", description: "Area above price below demand curve" },
    { name: "Producer Surplus", latex: "PS = \\dfrac{1}{2}(P - P_{\\min})\\times Q", description: "Area below price above supply curve" },
    { name: "Herfindahl-Hirschman Index", latex: "HHI = \\sum_{i=1}^n s_i^2", description: "s = market share %; measures concentration" },
      { name: "Average Fixed Cost", latex: "AFC = \\dfrac{FC}{Q}", description: "Fixed cost per unit" },
    { name: "Average Revenue", latex: "AR = \\dfrac{TR}{Q} = P", description: "Revenue per unit (= price in perfect competition)" },
    { name: "Average Total Cost", latex: "ATC = \\dfrac{TC}{Q}", description: "Total cost per unit" },
    { name: "Average Variable Cost", latex: "AVC = \\dfrac{VC}{Q}", description: "Variable cost per unit" },
    { name: "Concentration Ratio (CR4)", latex: "CR_4 = s_1 + s_2 + s_3 + s_4", description: "Market share of top 4 firms" },
    { name: "Cross Elasticity of Demand", latex: "XED = \\dfrac{\\%\\Delta Q_{d,A}}{\\%\\Delta P_B}", description: "Positive = substitutes; negative = complements" },
    { name: "Deadweight Loss", latex: "DWL = \\dfrac{1}{2}|P - MC|\\times|Q^* - Q_m|", description: "Welfare loss from market distortion" },
    { name: "Income Elasticity of Demand", latex: "YED = \\dfrac{\\%\\Delta Q_d}{\\%\\Delta Y}", description: "Responsiveness to income change" },
    { name: "Lerner Index", latex: "L = \\dfrac{P - MC}{P} = \\dfrac{-1}{PED}", description: "Measures market power (0 = competitive)" },
    { name: "Marginal Cost", latex: "MC = \\dfrac{\\Delta TC}{\\Delta Q}", description: "Extra cost of one more unit" },
    { name: "Marginal Revenue", latex: "MR = \\dfrac{\\Delta TR}{\\Delta Q}", description: "Extra revenue from one more unit" },
    { name: "Total Cost", latex: "TC = FC + VC", description: "Fixed plus variable costs" },
  ]),
  cat("Finance", [
    { name: "Net Present Value", latex: "NPV = \\sum_{t=0}^n \\dfrac{CF_t}{(1+r)^t}", description: "Sum of discounted cash flows" },
    { name: "Gini Coefficient", latex: "G = \\dfrac{A}{A+B}", description: "A = area between Lorenz curve and equality line" },
      { name: "Interest Rate Parity", latex: "\\dfrac{F}{S} = \\dfrac{1+i_d}{1+i_f}", description: "F=forward rate, S=spot rate" },
  ]),
];

function hydrateSheet(
  subjectId: string,
  subjectName: string,
  raw: { name: string; formulas: RawFormula[] }[]
): FormulaSheet {
  return {
    subjectId,
    subjectName,
    categories: raw.map((c) => ({
      name: c.name,
      formulas: c.formulas.map((f): Formula => ({
        id: f.id,
        name: f.name,
        latex: f.latex,
        description: f.description,
        subjectId,
        category: c.name,
      })),
    })),
  };
}

export const FORMULA_SHEET_DATA: FormulaSheet[] = [
  hydrateSheet("math", "Mathematics", MATH_CATEGORIES),
  hydrateSheet("physics", "Physics", PHYSICS_CATEGORIES),
  hydrateSheet("chemistry", "Chemistry", CHEMISTRY_CATEGORIES),
  hydrateSheet("biology", "Biology", BIOLOGY_CATEGORIES),
  hydrateSheet("economics", "Economics", ECONOMICS_CATEGORIES),
];

export function findFormulaSheet(subjectId: string): FormulaSheet | undefined {
  return FORMULA_SHEET_DATA.find((s) => s.subjectId === subjectId);
}

export function buildFormulaSheetContext(subjectId: string): string {
  const sheet = findFormulaSheet(subjectId);
  if (!sheet) return "";
  const lines: string[] = [];
  for (const cat of sheet.categories) {
    for (const f of cat.formulas) {
      lines.push(`• ${f.name} (${cat.name}): ${f.description} → ${f.latex}`);
    }
  }
  return `Formula sheet for ${sheet.subjectName}:\n${lines.join("\n")}`;
}

export function searchAllFormulas(query: string): Formula[] {
  const q = query.toLowerCase();
  const results: Formula[] = [];
  for (const sheet of FORMULA_SHEET_DATA) {
    for (const cat of sheet.categories) {
      for (const f of cat.formulas) {
        if (f.name.toLowerCase().includes(q) || f.description?.toLowerCase().includes(q)) {
          results.push(f);
        }
      }
    }
  }
  return results;
}
