export const INTERESTS = [
  { value: 'cricket', label: 'Cricket', icon: '🏏', category: 'Sports' },
  { value: 'afl', label: 'AFL', icon: '🏈', category: 'Sports' },
  { value: 'soccer', label: 'Soccer', icon: '⚽', category: 'Sports' },
  { value: 'formula 1', label: 'Formula 1', icon: '🏎️', category: 'Sports' },
  { value: 'basketball', label: 'Basketball', icon: '🏀', category: 'Sports' },
  { value: 'minecraft', label: 'Minecraft', icon: '⛏️', category: 'Games' },
  { value: 'roblox', label: 'Roblox', icon: '𝗥⟐𝗕𝗟◘𝗫', category: 'Games' },
  { value: 'fortnite', label: 'Fortnite', icon: '🪂', category: 'Games' },
  { value: 'chess', label: 'Chess', icon: '♟️', category: 'Games' },
  { value: 'movies', label: 'Movies', icon: '🎬', category: 'Entertainment' },
  { value: 'anime', label: 'Anime', icon: '⛩️', category: 'Entertainment' },
  { value: 'music', label: 'Music', icon: '🎵', category: 'Entertainment' },
  { value: 'coding', label: 'Coding', icon: '💻', category: 'Technology' },
  { value: 'gadgets', label: 'Gadgets', icon: '📱', category: 'Technology' },
  { value: 'space', label: 'Space', icon: '🚀', category: 'Exploration' },
  { value: 'cars', label: 'Cars', icon: '🚗', category: 'Vehicles' },
  { value: 'motorbikes', label: 'Motorbikes', icon: '🏍️', category: 'Vehicles' },
  { value: 'trains', label: 'Trains', icon: '🚃', category: 'Vehicles' },
  { value: 'cooking', label: 'Cooking', icon: '🍳', category: 'Hobbies' },
  { value: 'photography', label: 'Photography', icon: '📸', category: 'Hobbies' },
  { value: 'knitting', label: 'Knitting', icon: '🧶', category: 'Hobbies' },
  { value: 'art', label: 'Art & Design', icon: '🎨', category: 'Creative' },
];
