import type { GraphQLContext } from "../context.js";

interface Link {
  title: string;
  url: string;
  description?: string;
  free?: boolean;
  states?: string[];
}

interface SubjectResources {
  subjectId: string;
  pastPapers: Link[];
  textbooks: Link[];
}

const DATA: SubjectResources[] = [
  {
    subjectId: "math",
    pastPapers: [
      { title: "NSW HSC Mathematics – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Mathematics", description: "Advanced, Ext 1, Ext 2, Standard 1 & 2 papers", free: true, states: ["NSW"] },
      { title: "VCE Mathematical Methods – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/mathematical-methods", free: true, states: ["VIC"] },
      { title: "VCE Specialist Mathematics – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/specialist-mathematics", free: true, states: ["VIC"] },
      { title: "VCE General Mathematics – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/general-mathematics", free: true, states: ["VIC"] },
      { title: "QCAA General Mathematics – Past SEE Papers", url: "https://www.qcaa.qld.edu.au/senior/see/subject-resources/mathematics-general", free: true, states: ["QLD"] },
      { title: "QCAA Mathematical Methods – Past SEE Papers", url: "https://www.qcaa.qld.edu.au/senior/see/subject-resources/mathematics-methods", free: true, states: ["QLD"] },
      { title: "QCAA Specialist Mathematics – Past SEE Papers", url: "https://www.qcaa.qld.edu.au/senior/see/subject-resources/mathematics-specialist", free: true, states: ["QLD"] },
      { title: "WA ATAR Mathematics Applications – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/mathematics-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "WA ATAR Mathematics Methods – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/mathematics-methods-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "WA ATAR Mathematics Specialist – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/mathematics-specialist-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE General Mathematics – Past Exams", url: "https://www.sace.sa.edu.au/web/general-mathematics/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "SACE Mathematical Methods – Past Exams", url: "https://www.sace.sa.edu.au/web/mathematical-methods/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "SACE Specialist Mathematics – Past Exams", url: "https://www.sace.sa.edu.au/web/specialist-mathematics/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "TASC Mathematics – Previous Exam Papers", url: "https://www.tasc.tas.gov.au/students/years-11-and-12/preparing-for-exams/previous-exam-papers/", free: true, states: ["TAS"] },
      { title: "BSSS Mathematics – ACT Senior Secondary", url: "https://www.bsss.act.edu.au/student_programs/courses/mathematics", free: true, states: ["ACT"] },
      { title: "NAPLAN Numeracy Practice (Years 7 & 9)", url: "https://www.nap.edu.au/naplan/public-demonstration-site", free: true },
      { title: "THSC Online – Maths Trial Papers", url: "https://thsconline.github.io/s/yr12/Mathematics/", free: true, states: ["NSW"] },
      { title: "AceHSC – Mathematics Trial Papers", url: "https://www.acehsc.net/category/past-trial-papers/", free: true, states: ["NSW"] },
      { title: "Matrix Education – HSC Maths Worked Solutions", url: "https://www.matrix.edu.au/hsc-solutions/", free: true, states: ["NSW"] },
      { title: "Talent 100 – Free Maths Downloads", url: "https://talent-100.com.au/free-downloads/", free: true, states: ["NSW"] },
      { title: "HSCPastPapers.com – Mathematics", url: "https://www.hscpastpapers.com/", free: true, states: ["NSW"] },
      { title: "itute.com – Free VCE Maths Exams & Solutions", url: "https://www.itute.com/download-free-vce-maths-resources/free-maths-exams/", free: true, states: ["VIC"] },
      { title: "Art of Smart – Maths Past Papers", url: "https://artofsmart.com.au/learn/hsc-past-papers/", free: true },
      { title: "Physics & Maths Tutor – Maths by Topic", url: "https://www.physicsandmathstutor.com/maths-revision/", free: true },
      { title: "Khan Academy – Maths Practice", url: "https://www.khanacademy.org/math", free: true },
      { title: "AMT Australian Mathematics Competition – Past Papers", url: "https://www.amt.edu.au/competitions/amc", free: true },
    ],
    textbooks: [
      { title: "OpenStax Algebra and Trigonometry 2e", url: "https://openstax.org/details/books/algebra-and-trigonometry-2e", free: true },
      { title: "OpenStax Precalculus 2e", url: "https://openstax.org/details/books/precalculus-2e", free: true },
      { title: "OpenStax Calculus Volume 1", url: "https://openstax.org/details/books/calculus-volume-1", free: true },
      { title: "OpenStax Calculus Volume 2", url: "https://openstax.org/details/books/calculus-volume-2", free: true },
      { title: "OpenStax Calculus Volume 3", url: "https://openstax.org/details/books/calculus-volume-3", free: true },
      { title: "OpenStax Introductory Statistics", url: "https://openstax.org/details/books/introductory-statistics", free: true },
      { title: "Paul's Online Math Notes", url: "https://tutorial.math.lamar.edu/", free: true },
      { title: "Khan Academy – Mathematics", url: "https://www.khanacademy.org/math", free: true },
      { title: "MIT OpenCourseWare – Mathematics", url: "https://ocw.mit.edu/courses/mathematics/", free: true },
      { title: "3Blue1Brown (YouTube)", url: "https://www.youtube.com/c/3blue1brown", free: true },
      { title: "Wolfram MathWorld", url: "https://mathworld.wolfram.com/", free: true },
      { title: "LibreTexts Mathematics", url: "https://math.libretexts.org/", free: true },
      { title: "Desmos Graphing Calculator", url: "https://www.desmos.com/calculator", free: true },
      { title: "GeoGebra – Interactive Maths", url: "https://www.geogebra.org/", free: true },
    ],
  },
  {
    subjectId: "physics",
    pastPapers: [
      { title: "NSW HSC Physics – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Physics", free: true, states: ["NSW"] },
      { title: "VCE Physics – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/physics", free: true, states: ["VIC"] },
      { title: "QCAA Physics – Past SEE Papers", url: "https://www.qcaa.qld.edu.au/senior/see/subject-resources/physics", free: true, states: ["QLD"] },
      { title: "WA ATAR Physics – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/physics-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Physics – Past Exams", url: "https://www.sace.sa.edu.au/web/physics/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – Physics Trial Papers", url: "https://thsconline.github.io/s/yr12/Physics/", free: true, states: ["NSW"] },
      { title: "Matrix Education – HSC Physics Worked Solutions", url: "https://www.matrix.edu.au/hsc-solutions/", free: true, states: ["NSW"] },
      { title: "itute.com – Free VCE Physics Exams + Solutions", url: "https://www.itute.com/download-free-vce-physics-resources/free-physics-exams/", free: true, states: ["VIC"] },
      { title: "Physics & Maths Tutor – Physics by Topic", url: "https://www.physicsandmathstutor.com/physics-revision/", free: true },
      { title: "Isaac Physics – Problem Sets", url: "https://isaacphysics.org/", free: true },
      { title: "Australian Science Olympiad – Physics Papers", url: "https://www.aso.edu.au/", free: true },
      { title: "Khan Academy – Physics Practice", url: "https://www.khanacademy.org/science/physics", free: true },
    ],
    textbooks: [
      { title: "The Feynman Lectures on Physics", url: "https://www.feynmanlectures.caltech.edu/", free: true },
      { title: "OpenStax University Physics Vol 1", url: "https://openstax.org/details/books/university-physics-volume-1", free: true },
      { title: "OpenStax University Physics Vol 2", url: "https://openstax.org/details/books/university-physics-volume-2", free: true },
      { title: "OpenStax University Physics Vol 3", url: "https://openstax.org/details/books/university-physics-volume-3", free: true },
      { title: "OpenStax College Physics 2e", url: "https://openstax.org/details/books/college-physics-2e", free: true },
      { title: "Khan Academy – Physics", url: "https://www.khanacademy.org/science/physics", free: true },
      { title: "HyperPhysics", url: "http://hyperphysics.phy-astr.gsu.edu/hbase/hframe.html", free: true },
      { title: "PhET – Physics Simulations", url: "https://phet.colorado.edu/en/simulations/filter?subjects=physics", free: true },
      { title: "LibreTexts Physics", url: "https://phys.libretexts.org/", free: true },
      { title: "MIT OCW – Physics Courses", url: "https://ocw.mit.edu/courses/physics/", free: true },
      { title: "Physics Classroom", url: "https://www.physicsclassroom.com/", free: true },
    ],
  },
  {
    subjectId: "chemistry",
    pastPapers: [
      { title: "NSW HSC Chemistry – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Chemistry", free: true, states: ["NSW"] },
      { title: "VCE Chemistry – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/chemistry", free: true, states: ["VIC"] },
      { title: "QCAA Chemistry – Past SEE Papers", url: "https://www.qcaa.qld.edu.au/senior/see/subject-resources/chemistry", free: true, states: ["QLD"] },
      { title: "WA ATAR Chemistry – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/chemistry-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Chemistry – Past Exams", url: "https://www.sace.sa.edu.au/web/chemistry/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – Chemistry Trial Papers", url: "https://thsconline.github.io/s/yr12/Chemistry/", free: true, states: ["NSW"] },
      { title: "Matrix Education – HSC Chemistry Worked Solutions", url: "https://www.matrix.edu.au/hsc-solutions/", free: true, states: ["NSW"] },
      { title: "itute.com – Free VCE Chemistry Exams", url: "https://www.itute.com/", free: true, states: ["VIC"] },
      { title: "Physics & Maths Tutor – Chemistry by Topic", url: "https://www.physicsandmathstutor.com/chemistry-revision/", free: true },
      { title: "Australian Science Olympiad – Chemistry Papers", url: "https://www.aso.edu.au/", free: true },
      { title: "Khan Academy – Chemistry Practice", url: "https://www.khanacademy.org/science/chemistry", free: true },
    ],
    textbooks: [
      { title: "OpenStax Chemistry 2e", url: "https://openstax.org/details/books/chemistry-2e", free: true },
      { title: "OpenStax Chemistry: Atoms First 2e", url: "https://openstax.org/details/books/chemistry-atoms-first-2e", free: true },
      { title: "LibreTexts Chemistry", url: "https://chem.libretexts.org/", free: true },
      { title: "Khan Academy – Chemistry", url: "https://www.khanacademy.org/science/chemistry", free: true },
      { title: "ChemGuide", url: "https://www.chemguide.co.uk/", free: true },
      { title: "PhET – Chemistry Simulations", url: "https://phet.colorado.edu/en/simulations/filter?subjects=chemistry", free: true },
      { title: "MIT OCW – Chemistry Courses", url: "https://ocw.mit.edu/courses/chemistry/", free: true },
      { title: "The Organic Chemistry Tutor (YouTube)", url: "https://www.youtube.com/c/TheOrganicChemistryTutor", free: true },
      { title: "Periodic Table – Royal Society of Chemistry", url: "https://www.rsc.org/periodic-table/", free: true },
      { title: "Chemspider – Chemical Database", url: "https://www.chemspider.com/", free: true },
    ],
  },
  {
    subjectId: "biology",
    pastPapers: [
      { title: "NSW HSC Biology – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Biology", free: true, states: ["NSW"] },
      { title: "VCE Biology – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/biology", free: true, states: ["VIC"] },
      { title: "QCAA Biology – Past SEE Papers", url: "https://www.qcaa.qld.edu.au/senior/see/subject-resources/biology", free: true, states: ["QLD"] },
      { title: "WA ATAR Biology – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/biology-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Biology – Past Exams", url: "https://www.sace.sa.edu.au/web/biology/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – Biology Trial Papers", url: "https://thsconline.github.io/s/yr12/Biology/", free: true, states: ["NSW"] },
      { title: "Matrix Education – HSC Biology Worked Solutions", url: "https://www.matrix.edu.au/hsc-solutions/", free: true, states: ["NSW"] },
      { title: "Physics & Maths Tutor – Biology by Topic", url: "https://www.physicsandmathstutor.com/biology-revision/", free: true },
      { title: "Australian Science Olympiad – Biology Papers", url: "https://www.aso.edu.au/", free: true },
      { title: "Khan Academy – Biology Practice", url: "https://www.khanacademy.org/science/biology", free: true },
    ],
    textbooks: [
      { title: "OpenStax Biology 2e", url: "https://openstax.org/details/books/biology-2e", free: true },
      { title: "OpenStax Concepts of Biology", url: "https://openstax.org/details/books/concepts-biology", free: true },
      { title: "OpenStax Anatomy and Physiology 2e", url: "https://openstax.org/details/books/anatomy-and-physiology-2e", free: true },
      { title: "LibreTexts Biology", url: "https://bio.libretexts.org/", free: true },
      { title: "Khan Academy – Biology", url: "https://www.khanacademy.org/science/biology", free: true },
      { title: "NCBI Bookshelf – Molecular Biology of the Cell", url: "https://www.ncbi.nlm.nih.gov/books/", free: true },
      { title: "MIT OCW – Biology Courses", url: "https://ocw.mit.edu/courses/biology/", free: true },
      { title: "HHMI Biointeractive", url: "https://www.biointeractive.org/", free: true },
      { title: "PhET – Biology Simulations", url: "https://phet.colorado.edu/en/simulations/filter?subjects=biology", free: true },
      { title: "Scitable by Nature Education", url: "https://www.nature.com/scitable", free: true },
    ],
  },
  {
    subjectId: "english",
    pastPapers: [
      { title: "NSW HSC English – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=English", free: true, states: ["NSW"] },
      { title: "VCE English – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/english", free: true, states: ["VIC"] },
      { title: "VCE English Language – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/english-language", free: true, states: ["VIC"] },
      { title: "QCAA English – Past SEE Papers", url: "https://www.qcaa.qld.edu.au/senior/see/subject-resources/english", free: true, states: ["QLD"] },
      { title: "WA ATAR English – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/english-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE English – Past Exams", url: "https://www.sace.sa.edu.au/web/english/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "NAPLAN Reading & Writing Practice (Years 7 & 9)", url: "https://www.nap.edu.au/naplan/public-demonstration-site", free: true },
      { title: "THSC Online – English Trial Papers", url: "https://thsconline.github.io/s/yr12/English/", free: true, states: ["NSW"] },
      { title: "Matrix Education – HSC English Solutions", url: "https://www.matrix.edu.au/hsc-solutions/", free: true, states: ["NSW"] },
      { title: "Physics & Maths Tutor – English Resources", url: "https://www.physicsandmathstutor.com/english-revision/", free: true },
      { title: "ReadWriteThink – Writing Practice", url: "https://www.readwritethink.org/", free: true },
    ],
    textbooks: [
      { title: "Purdue OWL – Writing Lab", url: "https://owl.purdue.edu/owl/purdue_owl.html", free: true },
      { title: "Project Gutenberg – Classic Literature", url: "https://www.gutenberg.org/", free: true },
      { title: "SparkNotes – Study Guides", url: "https://www.sparknotes.com/", free: true },
      { title: "LitCharts – Literary Analysis", url: "https://www.litcharts.com/", free: true },
      { title: "No Fear Shakespeare", url: "https://www.sparknotes.com/nofear/", free: true },
      { title: "Khan Academy – Grammar", url: "https://www.khanacademy.org/humanities/grammar", free: true },
      { title: "BBC Learning English", url: "https://www.bbc.co.uk/learningenglish/", free: true },
      { title: "The Elements of Style – Strunk & White", url: "https://www.gutenberg.org/ebooks/37134", free: true },
      { title: "Grammarly Blog – Writing Resources", url: "https://www.grammarly.com/blog/", free: true },
      { title: "Vocabulary.com", url: "https://www.vocabulary.com/", free: true },
    ],
  },
  {
    subjectId: "history",
    pastPapers: [
      { title: "NSW HSC History – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=History", free: true, states: ["NSW"] },
      { title: "VCE History – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/history", free: true, states: ["VIC"] },
      { title: "QCAA Modern History – Past SEE Papers", url: "https://www.qcaa.qld.edu.au/senior/see/subject-resources/modern-history", free: true, states: ["QLD"] },
      { title: "WA ATAR Modern History – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/modern-history-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Modern History – Past Exams", url: "https://www.sace.sa.edu.au/web/modern-history/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – History Trial Papers", url: "https://thsconline.github.io/s/yr12/History/", free: true, states: ["NSW"] },
      { title: "Physics & Maths Tutor – History Questions", url: "https://www.physicsandmathstutor.com/history-revision/", free: true },
      { title: "Alpha History – Study Guides", url: "https://alphahistory.com/", free: true },
    ],
    textbooks: [
      { title: "Khan Academy – World History", url: "https://www.khanacademy.org/humanities/world-history", free: true },
      { title: "Internet History Sourcebooks Project", url: "https://sourcebooks.fordham.edu/", free: true },
      { title: "National Archives of Australia", url: "https://www.naa.gov.au/", free: true },
      { title: "Australian War Memorial", url: "https://www.awm.gov.au/", free: true },
      { title: "BBC History", url: "https://www.bbc.co.uk/history/", free: true },
      { title: "World History Encyclopedia", url: "https://www.worldhistory.org/", free: true },
    ],
  },
  {
    subjectId: "computing",
    pastPapers: [
      { title: "NSW HSC Software Design & Development – NESA", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Software%20Design%20and%20Development", free: true, states: ["NSW"] },
      { title: "VCE Software Development – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/software-development", free: true, states: ["VIC"] },
      { title: "QCAA Digital Solutions – Syllabus & Sample Papers", url: "https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/technologies/digital-solutions", free: true, states: ["QLD"] },
      { title: "WA ATAR Computer Science – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/computer-science-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "THSC Online – SDD & IPT Trial Papers", url: "https://thsconline.github.io/s/yr12/Software%20Design%20and%20Development/", free: true, states: ["NSW"] },
      { title: "Physics & Maths Tutor – A-Level Computer Science", url: "https://www.physicsandmathstutor.com/computer-science-revision/", free: true },
      { title: "CS50 Problem Sets (Harvard)", url: "https://cs50.harvard.edu/x/2024/psets/", free: true },
      { title: "Exercism – Coding Challenges", url: "https://exercism.org/", free: true },
      { title: "HackerRank – Programming Challenges", url: "https://www.hackerrank.com/", free: true },
    ],
    textbooks: [
      { title: "CS50 – Harvard Intro to Computer Science", url: "https://cs50.harvard.edu/x/", free: true },
      { title: "The Odin Project", url: "https://www.theodinproject.com/", free: true },
      { title: "Automate the Boring Stuff with Python", url: "https://automatetheboringstuff.com/", free: true },
      { title: "freeCodeCamp", url: "https://www.freecodecamp.org/", free: true },
      { title: "Eloquent JavaScript", url: "https://eloquentjavascript.net/", free: true },
      { title: "Khan Academy – Computing", url: "https://www.khanacademy.org/computing", free: true },
      { title: "MIT OCW – Introduction to CS", url: "https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/", free: true },
      { title: "GeeksforGeeks – CS Fundamentals", url: "https://www.geeksforgeeks.org/", free: true },
    ],
  },
  {
    subjectId: "economics",
    pastPapers: [
      { title: "NSW HSC Economics – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Economics", free: true, states: ["NSW"] },
      { title: "VCE Economics – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/economics", free: true, states: ["VIC"] },
      { title: "QCAA Economics – Syllabus & Sample Papers", url: "https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/humanities/economics", free: true, states: ["QLD"] },
      { title: "WA ATAR Economics – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/economics-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Economics – Past Exams", url: "https://www.sace.sa.edu.au/web/economics/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – Economics Trial Papers", url: "https://thsconline.github.io/s/yr12/Economics/", free: true, states: ["NSW"] },
      { title: "Physics & Maths Tutor – A-Level Economics", url: "https://www.physicsandmathstutor.com/economics-revision/", free: true },
      { title: "Tutor2u – Economics Revision", url: "https://www.tutor2u.net/economics", free: true },
      { title: "Reserve Bank of Australia – Education", url: "https://www.rba.gov.au/education/", free: true },
    ],
    textbooks: [
      { title: "OpenStax Principles of Economics 3e", url: "https://openstax.org/details/books/principles-economics-3e", free: true },
      { title: "OpenStax Microeconomics 3e", url: "https://openstax.org/details/books/principles-microeconomics-3e", free: true },
      { title: "OpenStax Macroeconomics 3e", url: "https://openstax.org/details/books/principles-macroeconomics-3e", free: true },
      { title: "Khan Academy – Macroeconomics", url: "https://www.khanacademy.org/economics-finance-domain/macroeconomics", free: true },
      { title: "Khan Academy – Microeconomics", url: "https://www.khanacademy.org/economics-finance-domain/microeconomics", free: true },
      { title: "Reserve Bank of Australia – Education", url: "https://www.rba.gov.au/education/", free: true },
      { title: "Tutor2u – Economics Notes", url: "https://www.tutor2u.net/economics", free: true },
      { title: "MRUniversity – Economics Videos", url: "https://mru.org/", free: true },
      { title: "CORE Economics Textbook", url: "https://www.core-econ.org/", free: true },
    ],
  },
  {
    subjectId: "geography",
    pastPapers: [
      { title: "NSW HSC Geography – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Geography", free: true, states: ["NSW"] },
      { title: "VCE Geography – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/geography", free: true, states: ["VIC"] },
      { title: "QCAA Geography – Syllabus & Sample Papers", url: "https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/humanities/geography", free: true, states: ["QLD"] },
      { title: "WA ATAR Geography – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/geography-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Geography – Past Exams", url: "https://www.sace.sa.edu.au/web/geography/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – Geography Trial Papers", url: "https://thsconline.github.io/s/yr12/Geography/", free: true, states: ["NSW"] },
      { title: "Physics & Maths Tutor – A-Level Geography", url: "https://www.physicsandmathstutor.com/geography-revision/", free: true },
    ],
    textbooks: [
      { title: "National Geographic Education", url: "https://education.nationalgeographic.org/", free: true },
      { title: "Geoscience Australia – Education", url: "https://www.ga.gov.au/education", free: true },
      { title: "Bureau of Meteorology – Climate Education", url: "http://www.bom.gov.au/climate/", free: true },
      { title: "Khan Academy – Earth and Space Science", url: "https://www.khanacademy.org/science/cosmology-and-astronomy", free: true },
      { title: "Our World in Data", url: "https://ourworldindata.org/", free: true },
      { title: "NASA Earth Observatory", url: "https://earthobservatory.nasa.gov/", free: true },
    ],
  },
  {
    subjectId: "business",
    pastPapers: [
      { title: "NSW HSC Business Studies – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Business%20Studies", free: true, states: ["NSW"] },
      { title: "VCE Business Management – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/business-management", free: true, states: ["VIC"] },
      { title: "QCAA Business – Syllabus & Sample Papers", url: "https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/business/business", free: true, states: ["QLD"] },
      { title: "WA ATAR Business Management – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/business-management-and-enterprise-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Business & Enterprise – Past Exams", url: "https://www.sace.sa.edu.au/web/business-and-enterprise/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – Business Studies Trial Papers", url: "https://thsconline.github.io/s/yr12/Business%20Studies/", free: true, states: ["NSW"] },
      { title: "Tutor2u – Business Revision", url: "https://www.tutor2u.net/business", free: true },
      { title: "Physics & Maths Tutor – A-Level Business", url: "https://www.physicsandmathstutor.com/business-studies-revision/", free: true },
      { title: "ASIC MoneySmart – Teaching Resources", url: "https://moneysmart.gov.au/teaching/", free: true },
    ],
    textbooks: [
      { title: "OpenStax Introduction to Business", url: "https://openstax.org/details/books/introduction-business", free: true },
      { title: "OpenStax Entrepreneurship", url: "https://openstax.org/details/books/entrepreneurship", free: true },
      { title: "Khan Academy – Finance & Markets", url: "https://www.khanacademy.org/economics-finance-domain/core-finance", free: true },
      { title: "ASIC MoneySmart", url: "https://moneysmart.gov.au/", free: true },
      { title: "Tutor2u – Business Notes", url: "https://www.tutor2u.net/business", free: true },
      { title: "MIT OCW – Sloan Management Courses", url: "https://ocw.mit.edu/courses/sloan-school-of-management/", free: true },
    ],
  },
  {
    subjectId: "pdhpe",
    pastPapers: [
      { title: "NSW HSC PDHPE – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Personal%20Development%2C%20Health%20and%20Physical%20Education", free: true, states: ["NSW"] },
      { title: "VCE Health & Human Development – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/health-and-human-development", free: true, states: ["VIC"] },
      { title: "VCE Physical Education – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/physical-education", free: true, states: ["VIC"] },
      { title: "QCAA Physical Education – Syllabus & Samples", url: "https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/health-pe/physical-education", free: true, states: ["QLD"] },
      { title: "WA ATAR Physical Education Studies – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/physical-education-studies-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Health – Past Exams", url: "https://www.sace.sa.edu.au/web/health/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – PDHPE Trial Papers", url: "https://thsconline.github.io/s/yr12/Personal%20Development%2C%20Health%20and%20Physical%20Education/", free: true, states: ["NSW"] },
      { title: "Physics & Maths Tutor – A-Level PE Questions", url: "https://www.physicsandmathstutor.com/pe-revision/", free: true },
      { title: "Khan Academy – Health & Medicine", url: "https://www.khanacademy.org/science/health-and-medicine", free: true },
    ],
    textbooks: [
      { title: "OpenStax Anatomy & Physiology 2e", url: "https://openstax.org/details/books/anatomy-and-physiology-2e", free: true },
      { title: "Khan Academy – Health & Medicine", url: "https://www.khanacademy.org/science/health-and-medicine", free: true },
      { title: "Better Health Channel", url: "https://www.betterhealth.vic.gov.au/", free: true },
      { title: "Australian Institute of Sport", url: "https://www.ais.gov.au/", free: true },
      { title: "WHO – Health Data", url: "https://www.who.int/data", free: true },
      { title: "Australian Institute of Health and Welfare", url: "https://www.aihw.gov.au/", free: true },
    ],
  },
  {
    subjectId: "engineering",
    pastPapers: [
      { title: "NSW HSC Engineering Studies – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Engineering%20Studies", free: true, states: ["NSW"] },
      { title: "VCE Engineering & Technology – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/engineering-and-technology", free: true, states: ["VIC"] },
      { title: "QCAA Engineering – Syllabus & Sample Papers", url: "https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/technologies/engineering", free: true, states: ["QLD"] },
      { title: "WA ATAR Engineering Science – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/engineering-science-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Engineering – Past Exams", url: "https://www.sace.sa.edu.au/web/engineering/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – Engineering Studies Trial Papers", url: "https://thsconline.github.io/s/yr12/Engineering%20Studies/", free: true, states: ["NSW"] },
      { title: "Isaac Physics – Engineering Problems", url: "https://isaacphysics.org/", free: true },
      { title: "Khan Academy – Electrical Engineering", url: "https://www.khanacademy.org/science/electrical-engineering", free: true },
    ],
    textbooks: [
      { title: "OpenStax University Physics Vol 1 (Mechanics)", url: "https://openstax.org/details/books/university-physics-volume-1", free: true },
      { title: "OpenStax University Physics Vol 2 (E&M)", url: "https://openstax.org/details/books/university-physics-volume-2", free: true },
      { title: "The Engineering Toolbox", url: "https://www.engineeringtoolbox.com/", free: true },
      { title: "Khan Academy – Electrical Engineering", url: "https://www.khanacademy.org/science/electrical-engineering", free: true },
      { title: "HyperPhysics – Mechanics & Thermodynamics", url: "http://hyperphysics.phy-astr.gsu.edu/hbase/hframe.html", free: true },
      { title: "LibreTexts – Engineering", url: "https://eng.libretexts.org/", free: true },
    ],
  },
  {
    subjectId: "medicine",
    pastPapers: [
      { title: "UCAT ANZ – Official Practice Tests", url: "https://www.ucat.edu.au/ucat-anz/practice-tests/", free: true },
      { title: "BMAT Past Papers", url: "https://www.admissionstesting.org/for-test-takers/bmat/preparing-for-bmat/", free: true },
      { title: "UCAT Ninja – Free Practice", url: "https://www.ucat.ninja/", free: true },
      { title: "NSW HSC Biology – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Biology", free: true, states: ["NSW"] },
      { title: "NSW HSC Chemistry – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Chemistry", free: true, states: ["NSW"] },
      { title: "VCE Biology – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/biology", free: true, states: ["VIC"] },
      { title: "VCE Chemistry – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/chemistry", free: true, states: ["VIC"] },
      { title: "GAMSAT Practice Questions – ACER", url: "https://gamsat.acer.org/preparation/", free: true },
      { title: "Khan Academy – MCAT Biology Practice", url: "https://www.khanacademy.org/test-prep/mcat", free: true },
    ],
    textbooks: [
      { title: "OpenStax Anatomy & Physiology 2e", url: "https://openstax.org/details/books/anatomy-and-physiology-2e", free: true },
      { title: "OpenStax Biology 2e", url: "https://openstax.org/details/books/biology-2e", free: true },
      { title: "OpenStax Chemistry 2e", url: "https://openstax.org/details/books/chemistry-2e", free: true },
      { title: "Khan Academy – MCAT Prep", url: "https://www.khanacademy.org/test-prep/mcat", free: true },
      { title: "NCBI Bookshelf – Medical Texts", url: "https://www.ncbi.nlm.nih.gov/books/", free: true },
      { title: "Teach Me Anatomy", url: "https://teachmeanatomy.info/", free: true },
      { title: "Teach Me Physiology", url: "https://teachmephysiology.com/", free: true },
    ],
  },
  {
    subjectId: "commerce",
    pastPapers: [
      { title: "NSW HSC Commerce – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Commerce", free: true, states: ["NSW"] },
      { title: "VCE Accounting – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/accounting", free: true, states: ["VIC"] },
      { title: "QCAA Accounting – Syllabus & Sample Papers", url: "https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/business/accounting", free: true, states: ["QLD"] },
      { title: "WA ATAR Accounting & Finance – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams/accounting-and-finance-past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Accounting – Past Exams", url: "https://www.sace.sa.edu.au/web/accounting/external-assessment", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – Commerce Trial Papers", url: "https://thsconline.github.io/s/yr12/Commerce/", free: true, states: ["NSW"] },
      { title: "Physics & Maths Tutor – A-Level Accounting", url: "https://www.physicsandmathstutor.com/accounting-revision/", free: true },
      { title: "Tutor2u – Accounting Revision", url: "https://www.tutor2u.net/accounting", free: true },
      { title: "Khan Academy – Accounting and Financial Statements", url: "https://www.khanacademy.org/economics-finance-domain/core-finance/accounting-and-financial-stateme", free: true },
    ],
    textbooks: [
      { title: "OpenStax Financial Accounting", url: "https://openstax.org/details/books/principles-financial-accounting", free: true },
      { title: "OpenStax Managerial Accounting", url: "https://openstax.org/details/books/principles-managerial-accounting", free: true },
      { title: "Khan Academy – Finance & Accounting", url: "https://www.khanacademy.org/economics-finance-domain/core-finance", free: true },
      { title: "ASIC MoneySmart", url: "https://moneysmart.gov.au/", free: true },
      { title: "AccountingCoach", url: "https://www.accountingcoach.com/", free: true },
      { title: "Tutor2u – Accounting Notes", url: "https://www.tutor2u.net/accounting", free: true },
    ],
  },
  {
    subjectId: "languages",
    pastPapers: [
      { title: "NSW HSC Languages – NESA Exam Papers", url: "https://www.nsw.gov.au/education-and-training/nesa/curriculum/hsc-exam-papers?category=Languages", free: true, states: ["NSW"] },
      { title: "VCE Languages – Past Exams (VCAA)", url: "https://www.vcaa.vic.edu.au/assessment/vce/examination-specifications-past-examinations-and-examination-reports/languages", free: true, states: ["VIC"] },
      { title: "QCAA Languages – Syllabuses & Sample Papers", url: "https://www.qcaa.qld.edu.au/senior/senior-subjects/syllabuses/languages", free: true, states: ["QLD"] },
      { title: "WA ATAR Languages – Past Exams (SCSA)", url: "https://senior-secondary.scsa.wa.edu.au/further-resources/past-atar-course-exams", free: true, states: ["WA"] },
      { title: "SACE Languages – Past Exams", url: "https://www.sace.sa.edu.au/studying/subjects/languages", free: true, states: ["SA", "NT"] },
      { title: "THSC Online – Languages Trial Papers", url: "https://thsconline.github.io/s/yr12/Languages/", free: true, states: ["NSW"] },
      { title: "JLPT Sample Questions (Japanese)", url: "https://www.jlpt.jp/e/samples/sampleindex.html", free: true },
      { title: "DELF Sample Papers (French)", url: "https://www.france-education-international.fr/diplome/delf-dalf", free: true },
      { title: "Goethe-Institut Practice Tests (German)", url: "https://www.goethe.de/en/spr/kup/ueb.html", free: true },
      { title: "HSK Sample Tests (Chinese Mandarin)", url: "https://www.chinesetest.cn/gosampletest.do", free: true },
    ],
    textbooks: [
      { title: "Duolingo", url: "https://www.duolingo.com/", free: true },
      { title: "BBC Learning English", url: "https://www.bbc.co.uk/learningenglish/", free: true },
      { title: "Anki – Spaced Repetition Flashcards", url: "https://apps.ankiweb.net/", free: true },
      { title: "Forvo – Pronunciation Dictionary", url: "https://forvo.com/", free: true },
      { title: "Language Transfer – Free Audio Courses", url: "https://www.languagetransfer.org/", free: true },
      { title: "NHK World – Japanese Lessons", url: "https://www3.nhk.or.jp/nhkworld/en/learnjapanese/", free: true },
      { title: "TV5Monde – French Media Resources", url: "https://apprendre.tv5monde.com/", free: true },
      { title: "Deutsche Welle – German Courses", url: "https://www.dw.com/en/learn-german/s-2469", free: true },
      { title: "WordReference – Dictionary & Forums", url: "https://www.wordreference.com/", free: true },
      { title: "Lingolia – Grammar & Exercises", url: "https://www.lingolia.com/en/", free: true },
    ],
  },
];

export const curatedResourceResolvers = {
  Query: {
    curatedResources: async (_: unknown, __: unknown, _ctx: GraphQLContext) => {
      return DATA;
    },
  },
};
